"""
This type stub file was generated by pyright.
"""


from .switches import SwitchError, switch

_translation = ...


class ShowHelp(SwitchError):
    ...


class ShowHelpAll(SwitchError):
    ...


class ShowVersion(SwitchError):
    ...


class SwitchParseInfo:
    __slots__ = ...

    def __init__(self, swname, val, index) -> None:
        ...


class Subcommand:

    def __init__(self, name, subapplication) -> None:
        ...

    def get(self):  # -> Any:
        ...

    def __repr__(self):  # -> str:
        ...

_switch_groups = ...
_switch_groups_l10n = ...


class Application:
    """The base class for CLI applications; your "entry point" class should derive from it,
    define the relevant switch functions and attributes, and the ``main()`` function.
    The class defines two overridable "meta switches" for version (``-v``, ``--version``)
    help (``-h``, ``--help``), and help-all (``--help-all``).

    The signature of the main function matters: any positional arguments (e.g., non-switch
    arguments) given on the command line are passed to the ``main()`` function; if you wish
    to allow unlimited number of positional arguments, use varargs (``*args``). The names
    of the arguments will be shown in the help message.

    The classmethod ``run`` serves as the entry point of the class. It parses the command-line
    arguments, invokes switch functions and enters ``main``. You should **not override** this
    method.

    Usage::

        class FileCopier(Application):
            stat = Flag("p", "copy stat info as well")

            def main(self, src, dst):
                if self.stat:
                    shutil.copy2(src, dst)
                else:
                    shutil.copy(src, dst)

        if __name__ == "__main__":
            FileCopier.run()

    There are several class-level attributes you may set:

    * ``PROGNAME`` - the name of the program; if ``None`` (the default), it is set to the
      name of the executable (``argv[0]``); can be in color. If only a color, will be applied to the name.

    * ``VERSION`` - the program's version (defaults to ``1.0``, can be in color)

    * ``DESCRIPTION`` - a short description of your program (shown in help). If not set,
      the class' ``__doc__`` will be used. Can be in color.

    * ``DESCRIPTION_MORE`` - a detailed description of your program (shown in help). The text will be printed
      by paragraphs (specified by empty lines between them). The indentation of each paragraph will be the
      indentation of its first line. List items are identified by their first non-whitespace character being
      one of '-', '*', and '/'; so that they are not combined with preceding paragraphs. Bullet '/' is
      "invisible", meaning that the bullet itself will not be printed to the output.

    * ``USAGE`` - the usage line (shown in help).

    * ``COLOR_USAGE_TITLE`` - The color of the usage line's header.

    * ``COLOR_USAGE`` - The color of the usage line.

    * ``COLOR_GROUPS`` - A dictionary that sets colors for the groups, like Meta-switches, Switches,
      and Subcommands.

    * ``COLOR_GROUP_TITLES`` - A dictionary that sets colors for the group titles. If the dictionary is empty,
      it defaults to ``COLOR_GROUPS``.

    * ``SUBCOMMAND_HELPMSG`` - Controls the printing of extra "see subcommand -h" help message.
      Default is a message, set to False to remove.

    * ``ALLOW_ABBREV`` - Controls whether partial switch names are supported, for example '--ver' will match
      '--verbose'. Default is False for backward consistency with previous plumbum releases. Note that ambiguous
      abbreviations will not match, for example if --foothis and --foothat are defined, then --foo will not match.

    A note on sub-commands: when an application is the root, its ``parent`` attribute is set to
    ``None``. When it is used as a nested-command, ``parent`` will point to its direct ancestor.
    Likewise, when an application is invoked with a sub-command, its ``nested_command`` attribute
    will hold the chosen sub-application and its command-line arguments (a tuple); otherwise, it
    will be set to ``None``

    """

    PROGNAME = ...
    DESCRIPTION = ...
    DESCRIPTION_MORE = ...
    VERSION = ...
    USAGE = ...
    COLOR_USAGE = ...
    COLOR_USAGE_TITLE = ...
    COLOR_GROUPS = ...
    COLOR_GROUP_TITLES = ...
    CALL_MAIN_IF_NESTED_COMMAND = ...
    SUBCOMMAND_HELPMSG = ...
    ALLOW_ABBREV = ...
    parent = ...
    nested_command = ...
    _unbound_switches = ...

    def __new__(cls, executable=...):  # -> tuple[Any | Self, Any | Literal[0, 1, 2]] | Self:
        """Allows running the class directly as a shortcut for main.
        This is necessary for some setup scripts that want a single function,
        instead of an expression with a dot in it."""
        ...

    def __init__(self, executable) -> None:
        ...
    @property

    def root_app(self):  # -> Self:
        ...

    @classmethod

    def unbind_switches(cls, *switch_names):  # -> None:
        """Unbinds the given switch names from this application. For example

        ::

            class MyApp(cli.Application):
                pass
            MyApp.unbind_switches("--version")

        """
        ...

    @classmethod

    def subcommand(cls, name, subapp=...):  # -> Callable[..., Any]:
        """Registers the given sub-application as a sub-command of this one. This method can be
        used both as a decorator and as a normal ``classmethod``::

            @MyApp.subcommand("foo")

            class FooApp(cli.Application):
                pass

        Or ::

            MyApp.subcommand("foo", FooApp)

        .. versionadded:: 1.1

        .. versionadded:: 1.3
            The sub-command can also be a string, in which case it is treated as a
            fully-qualified class name and is imported on demand. For example,

            MyApp.subcommand("foo", "fully.qualified.package.FooApp")

        """
        ...

    @classmethod

    def autocomplete(cls, argv):  # -> None:
        """This is supplied to make subclassing and testing argument completion methods easier"""
        ...

    @classmethod

    def run(cls, argv=..., exit=...):  # -> tuple[Any | Self, Any | Literal[0, 1, 2]]:
        """
        Runs the application, taking the arguments from ``sys.argv`` by default if
        nothing is passed. If ``exit`` is
        ``True`` (the default), the function will exit with the appropriate return code;
        otherwise it will return a tuple of ``(inst, retcode)``, where ``inst`` is the
        application instance created internally by this function and ``retcode`` is the
        exit code of the application.

        .. note::
           Setting ``exit`` to ``False`` is intended for testing/debugging purposes only -- do
           not override it in other situations.
        """
        ...

    @classmethod

    def invoke(cls, *args, **switches):  # -> tuple[Any | Self, Any | Literal[1, 0]]:
        """Invoke this application programmatically (as a function), in the same way ``run()``
        would. There are two key differences: the return value of ``main()`` is not converted to
        an integer (returned as-is), and exceptions are not swallowed either.

        :param args: any positional arguments for ``main()``
        :param switches: command-line switches are passed as keyword arguments,
                         e.g., ``foo=5`` for ``--foo=5``
        """
        ...

    def main(self, *args):  # -> Literal[1, 0]:
        """Implement me (no need to call super)"""
        ...

    def cleanup(self, retcode):  # -> None:
        """Called after ``main()`` and all sub-applications have executed, to perform any necessary cleanup.

        :param retcode: the return code of ``main()``
        """
        ...

    @switch(["--help-all"], overridable=True, group="Meta-switches", help=T_("""Prints help messages of all sub-commands and quits"""))

    def helpall(self):  # -> None:
        """Prints help messages of all sub-commands and quits"""
        ...

    @switch(["-h", "--help"], overridable=True, group="Meta-switches", help=T_("""Prints this help message and quits"""))

    def help(self):  # -> None:
        """Prints this help message and quits"""
        ...

    @switch(["-v", "--version"], overridable=True, group="Meta-switches", help=T_("""Prints the program's version and quits"""))

    def version(self):  # -> None:
        """Prints the program's version and quits"""
        ...
