"""
This type stub file was generated by pyright.
"""


from abc import ABC, abstractmethod


class ConfigBase(ABC):
    """Base class for Config parsers.

    :param filename: The file to use

    The ``with`` statement can be used to automatically try to read on entering and write if changed on exiting. Otherwise, use ``.read`` and ``.write`` as needed. Set and get the options using ``[]`` syntax.

    Usage:

        with Config("~/.myprog_rc") as conf:
            value = conf.get("option", "default")
            value2 = conf["option"] # shortcut for default=None

    """

    __slots__ = ...

    def __init__(self, filename) -> None:
        ...

    def __enter__(self):  # -> Self:
        ...

    def __exit__(self, exc_type, exc_val, exc_tb):  # -> None:
        ...

    @abstractmethod

    def read(self):  # -> None:
        """Read in the linked file"""
        ...

    @abstractmethod

    def write(self):  # -> None:
        """Write out the linked file"""
        ...

    def get(self, option, default=...):  # -> None:
        "Get an item from the store, returns default if fails"
        ...

    def set(self, option, value):  # -> None:
        """Set an item, mark this object as changed"""
        ...

    def __getitem__(self, option):  # -> None:
        ...

    def __setitem__(self, option, value):  # -> None:
        ...


class ConfigINI(ConfigBase):
    DEFAULT_SECTION = ...
    slots = ...

    def __init__(self, filename) -> None:
        ...

    def read(self):  # -> None:
        ...

    def write(self):  # -> None:
        ...

Config = ConfigINI
