"""
This type stub file was generated by pyright.
"""


import gettext

loc = ...


if loc is None or loc.startswith("en") or loc == "C":

    class NullTranslation:

        def gettext(self, str1: str) -> str:
            ...

        def ngettext(self, str1, strN, n):
            ...

    def get_translation_for(package_name: str) -> NullTranslation:
        ...

else:

    def get_translation_for(package_name: str) -> gettext.NullTranslations:
        """
        Find and return gettext translation for package
        """
        ...
