"""
This type stub file was generated by pyright.
"""


from abc import ABC, abstractmethod

"""
Progress bar
------------
"""


class ProgressBase(ABC):
    """Base class for progress bars. Customize for types of progress bars.

    :param iterator: The iterator to wrap with a progress bar
    :param length: The length of the iterator (will use ``__len__`` if None)
    :param timer: Try to time the completion status of the iterator
    :param body: True if the slow portion occurs outside the iterator (in a loop, for example)
    :param has_output: True if the iteration body produces output to the screen (forces rewrite off)
    :param clear: Clear the progress bar afterwards, if applicable.
    """

    def __init__(self, iterator=..., length=..., timer=..., body=..., has_output=..., clear=...) -> None:
        ...

    def __len__(self):  # -> int:
        ...

    def __iter__(self):  # -> Self:
        ...

    @abstractmethod

    def start(self):  # -> None:
        """This should initialize the progress bar and the iterator"""
        ...

    def __next__(self):
        ...

    def next(self):
        ...
    @property

    def value(self):
        """This is the current value, as a property so setting it can be customized"""
        ...

    @value.setter

    def value(self, val):  # -> None:
        ...

    @abstractmethod

    def display(self):  # -> None:
        """Called to update the progress bar"""
        ...

    def increment(self):  # -> None:
        """Sets next value and displays the bar"""
        ...

    def time_remaining(self):  # -> tuple[None, None] | tuple[timedelta, timedelta]:
        """Get the time remaining for the progress bar, guesses"""
        ...

    def str_time_remaining(self):  # -> str:
        """Returns a string version of time remaining"""
        ...

    @abstractmethod

    def done(self):  # -> None:
        """Is called when the iterator is done."""
        ...

    @classmethod

    def range(cls, *value, **kargs):  # -> Self:
        """Fast shortcut to create a range based progress bar, assumes work done in body"""
        ...

    @classmethod

    def wrap(cls, iterator, length=..., **kargs):  # -> Self:
        """Shortcut to wrap an iterator that does not do all the work internally"""
        ...


class Progress(ProgressBase):

    def start(self):  # -> None:
        ...

    def done(self):  # -> None:
        ...

    def __str__(self) -> str:
        ...

    def display(self):  # -> None:
        ...


class ProgressIPy(ProgressBase):
    HTMLBOX = ...

    def __init__(self, *args, **kargs) -> None:
        ...

    def start(self):  # -> None:
        ...

    @property

    def value(self):
        """This is the current value, -1 allowed (automatically fixed for display)"""
        ...

    @value.setter

    def value(self, val):  # -> None:
        ...

    def display(self):  # -> None:
        ...

    def done(self):  # -> None:
        ...


class ProgressAuto(ProgressBase):
    """Automatically selects the best progress bar (IPython HTML or text). Does not work with qtconsole
    (as that is correctly identified as identical to notebook, since the kernel is the same); it will still
    iterate, but no graphical indication will be displayed.

    :param iterator: The iterator to wrap with a progress bar
    :param length: The length of the iterator (will use ``__len__`` if None)
    :param timer: Try to time the completion status of the iterator
    :param body: True if the slow portion occurs outside the iterator (in a loop, for example)
    """

    def __new__(cls, *args, **kargs):  # -> ProgressIPy | Progress:
        """Uses the generator trick that if a cls instance is returned, the __init__ method is not called."""
        ...


def main():  # -> None:
    ...


if __name__ == "__main__":
    ...
