"""
This type stub file was generated by pyright.
"""


import collections.abc
from abc import ABC, abstractmethod
from typing import Callable

_translation = ...


class SwitchError(Exception):
    """A general switch related-error (base class of all other switch errors)"""

    ...


class PositionalArgumentsError(SwitchError):
    """Raised when an invalid number of positional arguments has been given"""

    ...


class SwitchCombinationError(SwitchError):
    """Raised when an invalid combination of switches has been given"""

    ...


class UnknownSwitch(SwitchError):
    """Raised when an unrecognized switch has been given"""

    ...


class MissingArgument(SwitchError):
    """Raised when a switch requires an argument, but one was not provided"""

    ...


class MissingMandatorySwitch(SwitchError):
    """Raised when a mandatory switch has not been given"""

    ...


class WrongArgumentType(SwitchError):
    """Raised when a switch expected an argument of some type, but an argument of a wrong
    type has been given"""

    ...


class SubcommandError(SwitchError):
    """Raised when there's something wrong with sub-commands"""

    ...


class SwitchInfo:

    def __init__(self, **kwargs) -> None:
        ...


def switch(names, argtype=..., argname=..., list=..., mandatory=..., requires=..., excludes=..., help=..., overridable=..., group=..., envname=...):  # -> Callable[..., Any]:
    """
    A decorator that exposes functions as command-line switches. Usage::

        class MyApp(Application):
            @switch(["-l", "--log-to-file"], argtype = str)

            def log_to_file(self, filename):
                handler = logging.FileHandler(filename)
                logger.addHandler(handler)

            @switch(["--verbose"], excludes=["--terse"], requires=["--log-to-file"])

            def set_debug(self):
                logger.setLevel(logging.DEBUG)

            @switch(["--terse"], excludes=["--verbose"], requires=["--log-to-file"])

            def set_terse(self):
                logger.setLevel(logging.WARNING)

    :param names: The name(s) under which the function is reachable; it can be a string
                  or a list of string, but at least one name is required. There's no need
                  to prefix the name with ``-`` or ``--`` (this is added automatically),
                  but it can be used for clarity. Single-letter names are prefixed by ``-``,
                  while longer names are prefixed by ``--``

    :param envname:   Name of environment variable to extract value from, as alternative to argv

    :param argtype: If this function takes an argument, you need to specify its type. The
                    default is ``None``, which means the function takes no argument. The type
                    is more of a "validator" than a real type; it can be any callable object
                    that raises a ``TypeError`` if the argument is invalid, or returns an
                    appropriate value on success. If the user provides an invalid value,
                    :func:`plumbum.cli.WrongArgumentType`

    :param argname: The name of the argument; if ``None``, the name will be inferred from the
                    function's signature

    :param list: Whether or not this switch can be repeated (e.g. ``gcc -I/lib -I/usr/lib``).
                 If ``False``, only a single occurrence of the switch is allowed; if ``True``,
                 it may be repeated indefinitely. The occurrences are collected into a list,
                 so the function is only called once with the collections. For instance,
                 for ``gcc -I/lib -I/usr/lib``, the function will be called with
                 ``["/lib", "/usr/lib"]``.

    :param mandatory: Whether or not this switch is mandatory; if a mandatory switch is not
                      given, :class:`MissingMandatorySwitch <plumbum.cli.MissingMandatorySwitch>`
                      is raised. The default is ``False``.

    :param requires: A list of switches that this switch depends on ("requires"). This means that
                     it's invalid to invoke this switch without also invoking the required ones.
                     In the example above, it's illegal to pass ``--verbose`` or ``--terse``
                     without also passing ``--log-to-file``. By default, this list is empty,
                     which means the switch has no prerequisites. If an invalid combination
                     is given, :class:`SwitchCombinationError <plumbum.cli.SwitchCombinationError>`
                     is raised.

                     Note that this list is made of the switch *names*; if a switch has more
                     than a single name, any of its names will do.

                     .. note::
                        There is no guarantee on the (topological) order in which the actual
                        switch functions will be invoked, as the dependency graph might contain
                        cycles.

    :param excludes: A list of switches that this switch forbids ("excludes"). This means that
                     it's invalid to invoke this switch if any of the excluded ones are given.
                     In the example above, it's illegal to pass ``--verbose`` along with
                     ``--terse``, as it will result in a contradiction. By default, this list
                     is empty, which means the switch has no prerequisites. If an invalid
                     combination is given, :class:`SwitchCombinationError
                     <plumbum.cli.SwitchCombinationError>` is raised.

                     Note that this list is made of the switch *names*; if a switch has more
                     than a single name, any of its names will do.

    :param help: The help message (description) for this switch; this description is used when
                 ``--help`` is given. If ``None``, the function's docstring will be used.

    :param overridable: Whether or not the names of this switch are overridable by other switches.
                        If ``False`` (the default), having another switch function with the same
                        name(s) will cause an exception. If ``True``, this is silently ignored.

    :param group: The switch's *group*; this is a string that is used to group related switches
                  together when ``--help`` is given. The default group is ``Switches``.

    :returns: The decorated function (with a ``_switch_info`` attribute)
    """
    ...


def autoswitch(*args, **kwargs):  # -> Callable[..., Any]:
    """A decorator that exposes a function as a switch, "inferring" the name of the switch
    from the function's name (converting to lower-case, and replacing underscores with hyphens).
    The arguments are the same as for :func:`switch <plumbum.cli.switch>`."""
    ...


class SwitchAttr:
    """
    A switch that stores its result in an attribute (descriptor). Usage::

        class MyApp(Application):
            logfile = SwitchAttr(["-f", "--log-file"], str)

            def main(self):
                if self.logfile:
                    open(self.logfile, "w")

    :param names: The switch names
    :param argtype: The switch argument's (and attribute's) type
    :param default: The attribute's default value (``None``)
    :param argname: The switch argument's name (default is ``"VALUE"``)
    :param kwargs: Any of the keyword arguments accepted by :func:`switch <plumbum.cli.switch>`
    """

    ATTR_NAME = ...
    VALUE = ...

    def __init__(self, names, argtype=..., default=..., list=..., argname=..., **kwargs) -> None:
        ...

    def __call__(self, inst, val):  # -> None:
        ...

    def __get__(self, inst, cls):  # -> Self | Any:
        ...

    def __set__(self, inst, val):  # -> None:
        ...


class Flag(SwitchAttr):
    """A specialized :class:`SwitchAttr <plumbum.cli.SwitchAttr>` for boolean flags. If the flag is not
    given, the value of this attribute is ``default``; if it is given, the value changes
    to ``not default``. Usage::

        class MyApp(Application):
            verbose = Flag(["-v", "--verbose"], help = "If given, I'll be very talkative")

    :param names: The switch names
    :param default: The attribute's initial value (``False`` by default)
    :param kwargs: Any of the keyword arguments accepted by :func:`switch <plumbum.cli.switch>`,
                   except for ``list`` and ``argtype``.
    """

    def __init__(self, names, default=..., **kwargs) -> None:
        ...

    def __call__(self, inst):  # -> None:
        ...


class CountOf(SwitchAttr):
    """A specialized :class:`SwitchAttr <plumbum.cli.SwitchAttr>` that counts the number of
    occurrences of the switch in the command line. Usage::

        class MyApp(Application):
            verbosity = CountOf(["-v", "--verbose"], help = "The more, the merrier")

    If ``-v -v -vv`` is given in the command-line, it will result in ``verbosity = 4``.

    :param names: The switch names
    :param default: The default value (0)
    :param kwargs: Any of the keyword arguments accepted by :func:`switch <plumbum.cli.switch>`,
                   except for ``list`` and ``argtype``.
    """

    def __init__(self, names, default=..., **kwargs) -> None:
        ...

    def __call__(self, inst, v):  # -> None:
        ...


class positional:
    """
    Runs a validator on the main function for a class.
    This should be used like this::

        class MyApp(cli.Application):
            @cli.positional(cli.Range(1,10), cli.ExistingFile)

            def main(self, x, *f):
                # x is a range, f's are all ExistingFile's)

    Or, Python 3 only::

        class MyApp(cli.Application):

            def main(self, x : cli.Range(1,10), *f : cli.ExistingFile):
                # x is a range, f's are all ExistingFile's)

    If you do not want to validate on the annotations, use this decorator (
    even if empty) to override annotation validation.

    Validators should be callable, and should have a ``.choices()`` function with
    possible choices. (For future argument completion, for example)

    Default arguments do not go through the validator.

    #TODO: Check with MyPy

    """

    def __init__(self, *args, **kargs) -> None:
        ...

    def __call__(self, function):
        ...


class Validator(ABC):
    __slots__ = ...
    @abstractmethod

    def __call__(self, obj):  # -> None:
        "Must be implemented for a Validator to work"
        ...

    def choices(self, partial=...):  # -> set[Any]:
        """Should return set of valid choices, can be given optional partial info"""
        ...

    def __repr__(self):  # -> str:
        """If not overridden, will print the slots as args"""
        ...


class Range(Validator):
    """
    A switch-type validator that checks for the inclusion of a value in a certain range.
    Usage::

        class MyApp(Application):
            age = SwitchAttr(["--age"], Range(18, 120))

    :param start: The minimal value
    :param end: The maximal value
    """

    __slots__ = ...

    def __init__(self, start, end) -> None:
        ...

    def __repr__(self):  # -> str:
        ...

    def __call__(self, obj):  # -> int:
        ...

    def choices(self, partial=...):  # -> set[int]:
        ...


class Set(Validator):
    """
    A switch-type validator that checks that the value is contained in a defined
    set of values. Usage::

        class MyApp(Application):
            mode = SwitchAttr(["--mode"], Set("TCP", "UDP", case_sensitive = False))
            num = SwitchAttr(["--num"], Set("MIN", "MAX", int, csv = True))

    :param values: The set of values (strings), or other callable validators, or types,
                   or any other object that can be compared to a string.
    :param case_sensitive: A keyword argument that indicates whether to use case-sensitive
                             comparison or not. The default is ``False``
    :param csv: splits the input as a comma-separated-value before validating and returning
                a list. Accepts ``True``, ``False``, or a string for the separator
    :param all_markers: When a user inputs any value from this set, all values are iterated
                        over. Something like {"*", "all"} would be a potential setting for
                        this option.
    """

    def __init__(self, *values: str | Callable[[str], str], case_sensitive: bool = ..., csv: bool | str = ..., all_markers: collections.abc.Set[str] = ...) -> None:
        ...

    def __repr__(self):  # -> str:
        ...

    def __call__(self, value: str, check_csv: bool = ...) -> str | list[str]:
        ...

    def choices(self, partial=...):  # -> set[str]:
        ...

CSV = ...


class Predicate:
    """A wrapper for a single-argument function with pretty printing"""

    def __init__(self, func) -> None:
        ...

    def __str__(self) -> str:
        ...

    def __call__(self, val):
        ...

    def choices(self, partial=...):  # -> set[Any]:
        ...

@Predicate


def ExistingDirectory(val):  # -> LocalPath:
    """A switch-type validator that ensures that the given argument is an existing directory"""
    ...

@Predicate


def MakeDirectory(val):  # -> LocalPath:
    ...

@Predicate


def ExistingFile(val):  # -> LocalPath:
    """A switch-type validator that ensures that the given argument is an existing file"""
    ...

@Predicate


def NonexistentPath(val):  # -> LocalPath:
    """A switch-type validator that ensures that the given argument is a nonexistent path"""
    ...
