"""
This type stub file was generated by pyright.
"""


"""
Terminal size utility
---------------------
"""


def get_terminal_size(default: tuple[int, int] = ...) -> tuple[int, int]:
    """
    Get width and height of console; works on linux, os x, windows and cygwin

    Adapted from https://gist.github.com/jtriley/1108174
    Originally from: http://stackoverflow.com/questions/566746/how-to-get-console-window-width-in-python
    """
    ...
