"""
This type stub file was generated by pyright.
"""


from typing import Iterable, NamedTuple

"""CLI interface for pytokens."""


class CLIArgs:
    filepath: str
    validate: bool
    issue_128233_handling: bool
    ...


def cli(argv: list[str] | None = ...) -> int:
    """CLI interface."""
    ...


class TokenTuple(NamedTuple):
    type: str
    start: tuple[int, int]
    end: tuple[int, int]
    ...


def validate(filepath: str, source: bytes, encoding: str, *, issue_128233_handling: bool, verbose: bool = ...) -> None:
    """Validate the source code."""
    ...


def find_all_python_files(directory: str) -> Iterable[str]:
    """Recursively find all Python files in the given directory."""
    ...
