"""
This type stub file was generated by pyright.
"""


import sys
from .factories import StyleFactory
from .styles import ANSIStyle, ColorNotFound, HTMLStyle, Style

"""\
The ``ansicolor`` object provides ``bg`` and ``fg`` to access colors,
and attributes like bold and
underlined text. It also provides ``reset`` to recover the normal font.
"""
__all__ = ("ANSIStyle", "ColorNotFound", "HTMLStyle", "Style", "StyleFactory", "ansicolors", "htmlcolors", "load_ipython_extension", "main")
ansicolors = ...
htmlcolors = ...


def load_ipython_extension(ipython):  # -> None:
    ...


def main():  # -> None:
    """Color changing script entry. Call using
    python3 -m plumbum.colors, will reset if no arguments given."""
    ...
