"""
This type stub file was generated by pyright.
"""


from IPython.core.magic import Magics, cell_magic, magics_class, needs_local_scope

valid_choices = ...

@magics_class


class OutputMagics(Magics):
    @needs_local_scope
    @cell_magic

    def to(self, line, cell, local_ns=...):  # -> None:
        ...
