"""
This type stub file was generated by pyright.
"""


from typing import Any

"""
Color-related factories. They produce Styles.
"""
__all__ = ["ColorFactory", "StyleFactory"]


class ColorFactory:
    """This creates color names given fg = True/False. It usually will
    be called as part of a StyleFactory."""

    def __init__(self, fg, style) -> None:
        ...

    def __getattr__(self, item):
        """Full color names work, but do not populate __dir__."""
        ...

    def full(self, name):
        """Gets the style for a color, using standard name procedure: either full
        color name, html code, or number."""
        ...

    def simple(self, name):
        """Return the extended color scheme color for a value or name."""
        ...

    def rgb(self, r, g=..., b=...):
        """Return the extended color scheme color for a value."""
        ...

    def hex(self, hexcode):
        """Return the extended color scheme color for a value."""
        ...

    def ansi(self, ansiseq):
        """Make a style from an ansi text sequence"""
        ...

    def __getitem__(self, val):  # -> list[Any]:
        """\
        Shortcut to provide way to access colors numerically or by slice.
        If end <= 16, will stay to simple ANSI version."""
        ...

    def __call__(self, val_or_r=..., g=..., b=...):
        """Shortcut to provide way to access colors."""
        ...

    def __iter__(self):  # -> Generator[Any, None, None]:
        """Iterates through all colors in extended colorset."""
        ...

    def __invert__(self):
        """Allows clearing a color with ~"""
        ...

    def __enter__(self):  # -> Self:
        """This will reset the color on leaving the with statement."""
        ...

    def __exit__(self, _type: Any, _value: Any, _traceback: Any) -> None:
        """This resets a FG/BG color or all styles,
        due to different definition of RESET for the
        factories."""
        ...

    def __repr__(self):  # -> str:
        """Simple representation of the class by name."""
        ...


class StyleFactory(ColorFactory):
    """Factory for styles. Holds font styles, FG and BG objects representing colors, and
    imitates the FG ColorFactory to a large degree."""

    def __init__(self, style) -> None:
        ...
    @property

    def use_color(self):
        """Shortcut for setting color usage on Style"""
        ...

    @use_color.setter

    def use_color(self, val):  # -> None:
        ...

    def from_ansi(self, ansi_sequence):
        """Calling this is a shortcut for creating a style from an ANSI sequence."""
        ...

    @property

    def stdout(self):  # -> TextIO | Any:
        """This is a shortcut for getting stdout from a class without an instance."""
        ...

    @stdout.setter

    def stdout(self, newout):  # -> None:
        ...

    def get_colors_from_string(self, color=...):  # -> Any | Self:
        """
        Sets color based on string, use `.` or space for separator,
        and numbers, fg/bg, htmlcodes, etc all accepted (as strings).
        """
        ...

    def filter(self, colored_string):
        """Filters out colors in a string, returning only the name."""
        ...

    def contains_colors(self, colored_string):
        """Checks to see if a string contains colors."""
        ...

    def extract(self, colored_string):
        """Gets colors from an ansi string, returns those colors"""
        ...

    def load_stylesheet(self, stylesheet=...):  # -> None:
        ...
