"""
This type stub file was generated by pyright.
"""


from abc import ABCMeta, abstractmethod
from typing import ClassVar, IO

"""
This file provides two classes, `Color` and `Style`.

``Color`` is rarely used directly,
but merely provides the workhorse for finding and manipulating colors.

With the ``Style`` class, any color can be directly called or given to a with statement.
"""
__all__ = ["ANSIStyle", "AttributeNotFound", "Color", "ColorNotFound", "HTMLStyle", "Style"]
_lower_camel_names = ...


def get_color_repr():  # -> int:
    """Gets best colors for current system."""
    ...


class ColorNotFound(Exception):
    """Thrown when a color is not valid for a particular method."""

    ...


class AttributeNotFound(Exception):
    """Similar to color not found, only for attributes."""

    ...


class ResetNotSupported(Exception):
    """An exception indicating that Reset is not available
    for this Style."""

    ...


class Color:
    """\
    Loaded with ``(r, g, b, fg)`` or ``(color, fg=fg)``. The second signature is a short cut
    and will try full and hex loading.

    This class stores the idea of a color, rather than a specific implementation.
    It provides as many different tools for representations as possible, and can be subclassed
    to add more representations, though that should not be needed for most situations. ``.from_`` class methods provide quick ways to create colors given different representations.
    You will not usually interact with this class.

    Possible colors::

        reset = Color() # The reset color by default
        background_reset = Color(fg=False) # Can be a background color
        blue = Color(0,0,255) # Red, Green, Blue
        green = Color.from_full("green") # Case insensitive name, from large colorset
        red = Color.from_full(1) # Color number
        white = Color.from_html("#FFFFFF") # HTML supported
        yellow = Color.from_simple("red") # Simple colorset

    The attributes are:

    .. data:: reset

        True it this is a reset color (following attributes don't matter if True)

    .. data:: rgb

        The red/green/blue tuple for this color

    .. data:: simple

        If true will stay to 16 color mode.

    .. data:: number

        The color number given the mode, closest to rgb
        if not rgb not exact, gives position of closest name.

    .. data:: fg

        This is a foreground color if True. Background color if False.

        """

    __slots__ = ...

    def __init__(self, r_or_color=..., g=..., b=..., fg=...) -> None:
        """This works from color values, or tries to load non-simple ones."""
        ...

    @classmethod

    def from_simple(cls, color, fg=...):  # -> Self:
        """Creates a color from simple name or color number"""
        ...

    @classmethod

    def from_full(cls, color, fg=...):  # -> Self:
        """Creates a color from full name or color number"""
        ...

    @classmethod

    def from_hex(cls, color, fg=...):  # -> Self:
        """Converts #123456 values to colors."""
        ...

    @property

    def name(self):  # -> Literal['reset']:
        """The (closest) name of the current color"""
        ...

    @property

    def name_camelcase(self):  # -> LiteralString:
        """The camelcase name of the color"""
        ...

    def __repr__(self):  # -> str:
        """This class has a smart representation that shows name and color (if not unique)."""
        ...

    def __eq__(self, other) -> bool:
        """Reset colors are equal, otherwise rgb have to match."""
        ...

    def __hash__(self) -> int:
        ...
    @property

    def ansi_sequence(self):  # -> str:
        """This is the ansi sequence as a string, ready to use."""
        ...

    @property

    def ansi_codes(
        self,
    ):  # -> tuple[Literal[39, 49]] | tuple[Any] | tuple[Literal[38, 48], Literal[5], int | None] | tuple[Literal[38, 48], Literal[2], Any | int | None, Any | int | None, Any | int | None]:
        """This is the full ANSI code, can be reset, simple, 256, or full color."""
        ...

    @property

    def hex_code(self):  # -> str:
        """This is the hex code of the current color, html style notation."""
        ...

    def __str__(self) -> str:
        """This just prints it's simple name"""
        ...

    def to_representation(self, val):  # -> Self:
        """Converts a color to any representation"""
        ...

    def limit_representation(self, val):  # -> Self:
        """Only converts if val is lower than representation"""
        ...


class Style(metaclass=ABCMeta):
    """This class allows the color changes to be called directly
    to write them to stdout, ``[]`` calls to wrap colors (or the ``.wrap`` method)
    and can be called in a with statement.
    """

    __slots__ = ...
    color_class = Color
    attribute_names: ClassVar[dict[str, str] | dict[str, int]]
    _stdout: IO | None = ...
    end = ...
    ANSI_REG = ...
    @property

    def stdout(self):  # -> IO[Any] | TextIO | Any:
        """\
        This property will allow custom, class level control of stdout.
        It will use current sys.stdout if set to None (default).
        Unfortunately, it only works on an instance..
        """
        ...

    @stdout.setter

    def stdout(self, newout):  # -> None:
        ...

    def __init__(self, attributes=..., fgcolor=..., bgcolor=..., reset=...) -> None:
        """This is usually initialized from a factory."""
        ...

    @classmethod

    def from_color(cls, color):  # -> Self:
        ...

    def invert(self):  # -> Self:
        """This resets current color(s) and flips the value of all
        attributes present"""
        ...

    @property

    def reset(self):  # -> Self:
        """Shortcut to access reset as a property."""
        ...

    def __copy__(self):  # -> Self:
        """Copy is supported, will make dictionary and colors unique."""
        ...

    def __invert__(self):  # -> Self:
        """This allows ~color."""
        ...

    def __add__(self, other):
        """Adding two matching Styles results in a new style with
        the combination of both. Adding with a string results in
        the string concatenation of a style.

        Addition is non-commutative, with the rightmost Style property
        being taken if both have the same property.
        (Not safe)"""
        ...

    def __radd__(self, other):
        """This only gets called if the string is on the left side. (Not safe)"""
        ...

    def wrap(self, wrap_this):
        """Wrap a string in this style and its inverse."""
        ...

    def __and__(self, other):
        """This class supports ``color & color2`` syntax,
        and ``color & "String" syntax too.``"""
        ...

    def __rand__(self, other):
        """This class supports ``"String:" & color`` syntax."""
        ...

    def __ror__(self, other):
        """Support for "String" | color syntax"""
        ...

    def __or__(self, other):
        """This class supports ``color | color2`` syntax. It also supports
        ``"color | "String"`` syntax too."""
        ...

    def __call__(self):  # -> None:
        """\
        This is a shortcut to print color immediately to the stdout. (Not safe)
        """
        ...

    def now(self):  # -> None:
        """Immediately writes color to stdout. (Not safe)"""
        ...

    def print(self, *printables, **kargs):  # -> None:
        """\
        This acts like print; will print that argument to stdout wrapped
        in Style with the same syntax as the print function in 3.4."""
        ...
    print_ = ...

    def __getitem__(self, wrapped):
        """The [] syntax is supported for wrapping"""
        ...

    def __enter__(self):  # -> None:
        """Context manager support"""
        ...

    def __exit__(self, _type, _value, _traceback):  # -> Literal[False]:
        """Runs even if exception occurred, does not catch it."""
        ...

    @property

    def ansi_codes(self):  # -> list[int] | list[Any]:
        """Generates the full ANSI code sequence for a Style"""
        ...

    @property

    def ansi_sequence(self):  # -> str:
        """This is the string ANSI sequence."""
        ...

    def __repr__(self):  # -> str:
        ...

    def __eq__(self, other) -> bool:
        """Equality is true only if reset, or if attributes, fg, and bg match."""
        ...
    __hash__ = ...
    @abstractmethod

    def __str__(self) -> str:
        """Base Style does not implement a __str__ representation. This is the one
        required method of a subclass."""
        ...

    @classmethod

    def from_ansi(cls, ansi_string, filter_resets=...):  # -> Self:
        """This generated a style from an ansi string. Will ignore resets if filter_resets is True."""
        ...

    def add_ansi(self, sequence, filter_resets=...):
        """Adds a sequence of ansi numbers to the class. Will ignore resets if filter_resets is True."""
        ...

    @classmethod

    def string_filter_ansi(cls, colored_string):  # -> str:
        """Filters out colors in a string, returning only the name."""
        ...

    @classmethod

    def string_contains_colors(cls, colored_string):  # -> bool:
        """Checks to see if a string contains colors."""
        ...

    def to_representation(self, rep):  # -> Self:
        """This converts both colors to a specific representation"""
        ...

    def limit_representation(self, rep):  # -> Self:
        """This only converts if true representation is higher"""
        ...

    @property

    def basic(self):  # -> Self:
        """The color in the 8 color representation."""
        ...

    @property

    def simple(self):  # -> Self:
        """The color in the 16 color representation."""
        ...

    @property

    def full(self):  # -> Self:
        """The color in the 256 color representation."""
        ...

    @property

    def true(self):  # -> Self:
        """The color in the true color representation."""
        ...


class ANSIStyle(Style):
    """This is a subclass for ANSI styles. Use it to get
    color on sys.stdout tty terminals on posix systems.

    Set ``use_color = True/False`` if you want to control color
    for anything using this Style."""

    __slots__ = ...
    use_color = ...
    attribute_names = ...

    def __str__(self) -> str:
        ...


class HTMLStyle(Style):
    """This was meant to be a demo of subclassing Style, but
    actually can be a handy way to quickly color html text."""

    __slots__ = ...
    attribute_names = ...
    end = ...

    def __str__(self) -> str:
        ...
