[tox]
envlist = py314, lint, type
skipsdist = True

[testenv]
deps =
    pytest
    pytest-cov
commands =
    pytest {posargs}

[testenv:lint]
deps =
    flake8
    black
    isort
commands =
    flake8 .
    black --check .
    isort --check-only .

[testenv:type]
deps =
    pyright
    .
commands =
    pyright
