"""
This type stub file was generated by pyright.
"""


from rpyc.core import (
    AsyncResult,
    AsyncResultTimeout,
    BaseNetref,
    Channel,
    ClassicService,
    Connection,
    GenericException,
    MasterService,
    PipeStream,
    Service,
    SlaveService,
    SocketStream,
    TunneledSocketStream,
    VoidService,
)
from rpyc.utils.factory import (
    connect,
    connect_by_service,
    connect_channel,
    connect_pipes,
    connect_stdpipes,
    connect_stream,
    connect_subproc,
    connect_thread,
    discover,
    list_services,
    ssh_connect,
    ssl_connect,
)
from rpyc.utils.helpers import BgServingThread, async_, buffiter, restricted, timed
from rpyc.utils import classic, exposed, service
from rpyc.version import __version__
from rpyc.lib import setup_logger, spawn
from rpyc.utils.server import ForkingServer, OneShotServer, ThreadPoolServer, ThreadedServer
from rpyc import cli

"""Remote Python Call (RPyC) is a transparent and symmetric distributed computing library
Licensed under the MIT license (see `LICENSE` file)

Usage::

    >>> import rpyc
    >>> c = rpyc.connect_by_service("SERVICENAME")
    >>> print(c.root.some_function(1, 2, 3))

Classic-style usage::

    >>> import rpyc
    >>> # `hostname` is assumed to be running a slave-service server
    >>> c = rpyc.classic.connect("hostname")
    >>> print(c.execute("x = 5"))
    None
    >>> print(c.eval("x + 2"))
    7
    >>> print(c.modules.os.listdir("."))  # doctest: +ELLIPSIS
    [...]
    >>> print(c.modules["xml.dom.minidom"].parseString("<a/>"))  # doctest: +ELLIPSIS
    <xml.dom.minidom.Document instance at ...>
    >>> f = c.builtin.open("foobar.txt", "rb")  # doctest: +SKIP
    >>> print(f.read(100))  # doctest: +SKIP
    ...

"""
__author__ = ...
