"""
This type stub file was generated by pyright.
"""


import inspect
import sys
import socket
import logging
import threading
import time
import random
from rpyc.lib.compat import maxint

"""
A library of various helpers functions and classes
"""
SPAWN_THREAD_PREFIX = ...


class MissingModule:
    __slots__ = ...

    def __init__(self, name) -> None:
        ...

    def __getattr__(self, name):
        ...

    def __bool__(self):  # -> Literal[False]:
        ...
    __nonzero__ = ...


def safe_import(name):  # -> Any | MissingModule:
    ...


def setup_logger(quiet=..., logfile=..., namespace=...):  # -> Logger:
    ...


class hybridmethod:
    """Decorator for hybrid instance/class methods that will act like a normal
    method if accessed via an instance, but act like classmethod if accessed
    via the class."""

    def __init__(self, func) -> None:
        ...

    def __get__(self, obj, cls):
        ...

    def __set__(self, obj, val):
        ...


def hasattr_static(obj, attr):  # -> bool:
    """Returns if `inspect.getattr_static` can find an attribute of ``obj``."""
    ...


def spawn(*args, **kwargs):  # -> Thread:
    """Start and return daemon thread. ``spawn(func, *args, **kwargs)``."""
    ...


def spawn_waitready(init, main):  # -> tuple[Thread, Event]:
    """
    Start a thread that runs ``init`` and then ``main``. Wait for ``init`` to
    be finished before returning.

    Returns a tuple ``(thread, init_result)``.
    """
    ...


class Timeout:

    def __init__(self, timeout) -> None:
        ...

    def expired(self):  # -> Literal[False]:
        ...

    def timeleft(self):  # -> Literal[0] | None:
        ...

    def sleep(self, interval):  # -> None:
        ...


def socket_backoff_connect(family, socktype, proto, addr, timeout, attempts):  # -> socket:
    """connect will backoff if the response is not ready for a pseudo random number greater than zero and less than
        51e-6, 153e-6, 358e-6, 768e-6, 1587e-6, 3225e-6, 6502e-6, 13056e-6, 26163e-6, 52377e-6
    this should help avoid congestion.
    """
    ...


def exp_backoff(collision):  # -> float:
    """Exponential backoff algorithm from
    Peterson, L.L., and Davie, B.S. Computer Networks: a systems approach. 5th ed. pp. 127
    """
    ...


def get_id_pack(obj):  # -> Any | object | tuple[Any | str | None, int, int] | tuple[str, int, int] | tuple[str, int, Literal[0]]:
    """introspects the given "local" object, returns id_pack as expected by
    BaseNetref

    The given object is "local" in the sense that it is from the local
    cache. Any object in the local cache exists in the current address
    space or is a netref. A netref in the local cache could be from a
    chained-connection. To handle type related behavior properly, the
    attribute `__class__` is a descriptor for netrefs.

    So, check thy assumptions regarding the given object when creating
    `id_pack`.
    """
    ...


def get_methods(obj_attrs, obj):  # -> dict_items[Any, Any]:
    """introspects the given (local) object, returning a list of all of its
    methods (going up the MRO).

    :param obj: any local (not proxy) python object

    :returns: a list of ``(method name, docstring)`` tuples of all the methods
              of the given object
    """
    ...
