"""
This type stub file was generated by pyright.
"""


class WeakValueDict:
    """a light-weight version of weakref.WeakValueDictionary"""

    __slots__ = ...

    def __init__(self) -> None:
        ...

    def __repr__(self):  # -> str:
        ...

    def __iter__(self):  # -> dict_keys[Any, Any]:
        ...

    def __len__(self):  # -> int:
        ...

    def __contains__(self, key):  # -> bool:
        ...

    def get(self, key, default=...):  # -> None:
        ...

    def __getitem__(self, key):
        ...

    def __setitem__(self, key, value):  # -> None:
        ...

    def __delitem__(self, key):  # -> None:
        ...

    def iterkeys(self):  # -> dict_keys[Any, Any]:
        ...

    def keys(self):  # -> dict_keys[Any, Any]:
        ...

    def itervalues(self):  # -> Generator[Any, Any, None]:
        ...

    def values(self):  # -> list[Any]:
        ...

    def iteritems(self):  # -> Generator[tuple[Any, Any], Any, None]:
        ...

    def items(self):  # -> list[tuple[Any, Any]]:
        ...

    def clear(self):  # -> None:
        ...


class RefCountingColl:
    """a set-like object that implements refcounting on its contained objects"""

    __slots__ = ...

    def __init__(self) -> None:
        ...

    def __repr__(self):  # -> str:
        ...

    def add(self, key, obj):  # -> None:
        """Add object to refcounting coll."""
        ...

    def clear(self):  # -> None:
        ...

    def decref(self, key, count=...):  # -> None:
        ...

    def __getitem__(self, key):
        ...
