"""
This type stub file was generated by pyright.
"""


import sys
import select as select_module

"""
compatibility module for various versions of python (2.4/3+/jython)
and various platforms (posix/windows)
"""
is_py_3k = ...
is_py_gte311 = ...
is_py_gte310 = ...
is_py_gte38 = ...
is_py_gte37 = ...


if is_py_3k:

    def BYTES_LITERAL(text):  # -> bytes:
        ...
    maxint = ...
else:

    def BYTES_LITERAL(text):
        ...

    maxint = ...
next = ...
callable = ...


def get_exc_errno(exc):
    ...


if select_module:
    select_error = select_module.error
else:
    select_error = IOError


if hasattr(select_module, "poll"):

    class PollingPoll:

        def __init__(self) -> None:
            ...

        def register(self, fd, mode):  # -> None:
            ...
        modify = ...

        def unregister(self, fd):  # -> None:
            ...

        def poll(self, timeout=...):  # -> list[Any]:
            ...

    poll = ...
else:

    class SelectingPoll:

        def __init__(self) -> None:
            ...

        def register(self, fd, mode):  # -> None:
            ...
        modify = ...

        def unregister(self, fd):  # -> None:
            ...

        def poll(self, timeout=...):  # -> list[Any] | list[tuple[Any, str]]:
            ...

    poll = ...


def with_metaclass(meta, *bases):  # -> metaclass:
    """Create a base class with a metaclass."""

    class metaclass(type):
        ...


if sys.version_info >= (3, 3):
    TimeoutError = TimeoutError
else:
    ...


if sys.version_info >= (3, 2):

    def acquire_lock(lock, blocking, timeout):
        ...

else:
    ...
