"""
This type stub file was generated by pyright.
"""


from plumbum.commands.base import BaseCommand, ConcreteCommand, ERROUT, shquote, shquote_list
from plumbum.commands.modifiers import BG, ExecutionModifier, FG, Future, NOHUP, RETCODE, TEE, TF
from plumbum.commands.processes import CommandNotFound, ProcessExecutionError, ProcessLineTimedOut, ProcessTimedOut, run_proc

__all__ = (
    "BG",
    "ERROUT",
    "FG",
    "NOHUP",
    "RETCODE",
    "TEE",
    "TF",
    "BaseCommand",
    "CommandNotFound",
    "ConcreteCommand",
    "ExecutionModifier",
    "Future",
    "ProcessExecutionError",
    "ProcessLineTimedOut",
    "ProcessTimedOut",
    "run_proc",
    "shquote",
    "shquote_list",
)


def __dir__():  # -> tuple[Literal['BG'], Literal['ERROUT'], Literal['FG'], Literal['NOHUP'], Literal['RETCODE'], Literal['TEE'], Literal['TF'], Literal['BaseCommand'], Literal['CommandNotFound'], Literal['ConcreteCommand'], Literal['ExecutionModifier'], Literal['Future'], Literal['ProcessExecutionError'], Literal['ProcessLineTimedOut'], Literal['ProcessTimedOut'], Literal['run_proc'], Literal['shquote'], Literal['shquote_list']]:
    ...
