"""
This type stub file was generated by pyright.
"""


import contextlib
from typing import ClassVar

__all__ = (
    "ERROUT",
    "AppendingStdoutRedirection",
    "BaseCommand",
    "BaseRedirection",
    "BoundCommand",
    "BoundEnvCommand",
    "ConcreteCommand",
    "Pipeline",
    "RedirectionError",
    "StderrRedirection",
    "StdinDataRedirection",
    "StdinRedirection",
    "StdoutRedirection",
    "iter_lines",
    "run_proc",
    "shquote",
    "shquote_list",
)


class RedirectionError(Exception):
    """Raised when an attempt is made to redirect an process' standard handle,
    which was already redirected to/from a file"""

    ...


def shquote(text):  # -> str:
    """Quotes the given text with shell escaping (assumes as syntax similar to ``sh``)"""
    ...


def shquote_list(seq):  # -> list[str]:
    ...


class BaseCommand:
    """Base of all command objects"""

    __slots__ = ...

    def __str__(self) -> str:
        ...

    def __or__(self, other):  # -> Pipeline:
        """Creates a pipe with the other command"""
        ...

    def __gt__(self, file) -> bool:
        """Redirects the process' stdout to the given file"""
        ...

    def __rshift__(self, file):  # -> AppendingStdoutRedirection:
        """Redirects the process' stdout to the given file (appending)"""
        ...

    def __ge__(self, file) -> bool:
        """Redirects the process' stderr to the given file"""
        ...

    def __lt__(self, file) -> bool:
        """Redirects the given file into the process' stdin"""
        ...

    def __lshift__(self, data):  # -> StdinDataRedirection:
        """Redirects the given data into the process' stdin"""
        ...

    def __getitem__(self, args):  # -> Self | BoundCommand:
        """Creates a bound-command with the given arguments. Shortcut for
        bound_command."""
        ...

    def bound_command(self, *args):  # -> Self | BoundCommand:
        """Creates a bound-command with the given arguments"""
        ...

    def __call__(self, *args, **kwargs):
        """A shortcut for `run(args)`, returning only the process' stdout"""
        ...

    def with_env(self, **env):  # -> Self | BoundEnvCommand:
        """Returns a BoundEnvCommand with the given environment variables"""
        ...

    def with_cwd(self, path):  # -> Self | BoundEnvCommand:
        """
        Returns a BoundEnvCommand with the specified working directory.
        This overrides a cwd specified in a wrapping `machine.cwd()` context manager.
        """
        ...
    setenv = ...
    @property

    def machine(self):
        ...

    def formulate(self, level=..., args=...):
        """Formulates the command into a command-line, i.e., a list of shell-quoted strings
        that can be executed by ``Popen`` or shells.

        :param level: The nesting level of the formulation; it dictates how much shell-quoting
                      (if any) should be performed

        :param args: The arguments passed to this command (a tuple)

        :returns: A list of strings
        """
        ...

    def popen(self, args=..., **kwargs):
        """Spawns the given command, returning a ``Popen``-like object.

        .. note::

           When processes run in the **background** (either via ``popen`` or
           :class:`& BG <plumbum.commands.BG>`), their stdout/stderr pipes might fill up,
           causing them to hang. If you know a process produces output, be sure to consume it
           every once in a while, using a monitoring thread/reactor in the background.
           For more info, see `#48 <https://github.com/tomerfiliba/plumbum/issues/48>`_

        :param args: Any arguments to be passed to the process (a tuple)

        :param kwargs: Any keyword-arguments to be passed to the ``Popen`` constructor

        :returns: A ``Popen``-like object
        """
        ...

    def nohup(self, cwd=..., stdout=..., stderr=..., append=...):
        """Runs a command detached."""
        ...

    @contextlib.contextmanager

    def bgrun(self, args=..., **kwargs):  # -> Generator[Any, Any, None]:
        """Runs the given command as a context manager, allowing you to create a
        `pipeline <http://en.wikipedia.org/wiki/Pipeline_(computing)>`_ (not in the UNIX sense)
        of programs, parallelizing their work. In other words, instead of running programs
        one after the other, you can start all of them at the same time and wait for them to
        finish. For a more thorough review, see
        `Lightweight Asynchronism <http://tomerfiliba.com/blog/Toying-with-Context-Managers/>`_.

        Example::

            from plumbum.cmd import mkfs

            with mkfs["-t", "ext3", "/dev/sda1"] as p1:
                with mkfs["-t", "ext3", "/dev/sdb1"] as p2:
                    pass

        .. note::

           When processes run in the **background** (either via ``popen`` or
           :class:`& BG <plumbum.commands.BG>`), their stdout/stderr pipes might fill up,
           causing them to hang. If you know a process produces output, be sure to consume it
           every once in a while, using a monitoring thread/reactor in the background.
           For more info, see `#48 <https://github.com/tomerfiliba/plumbum/issues/48>`_

        For the arguments, see :func:`run <BaseCommand.run>`.

        :returns: A Popen object, augmented with a ``.run()`` method, which returns a tuple of
                  (return code, stdout, stderr)
        """
        ...

    def run(self, args=..., **kwargs):
        """Runs the given command (equivalent to popen() followed by
        :func:`run_proc <plumbum.commands.run_proc>`). If the exit code of the process does
        not match the expected one, :class:`ProcessExecutionError
        <plumbum.commands.ProcessExecutionError>` is raised.

        :param args: Any arguments to be passed to the process (a tuple)

        :param retcode: The expected return code of this process (defaults to 0).
                        In order to disable exit-code validation, pass ``None``. It may also
                        be a tuple (or any iterable) of expected exit codes.

                        .. note:: this argument must be passed as a keyword argument.

        :param timeout: The maximal amount of time (in seconds) to allow the process to run.
                        ``None`` means no timeout is imposed; otherwise, if the process hasn't
                        terminated after that many seconds, the process will be forcefully
                        terminated an exception will be raised

                        .. note:: this argument must be passed as a keyword argument.

        :param kwargs: Any keyword-arguments to be passed to the ``Popen`` constructor

        :returns: A tuple of (return code, stdout, stderr)
        """
        ...

    def run_bg(self, **kwargs):  # -> Future:
        """
        Run this command in the background. Uses all arguments from the BG construct
        :py:class: `plumbum.commands.modifiers.BG`
        """
        ...

    def run_fg(self, **kwargs):  # -> None:
        """
        Run this command in the foreground. Uses all arguments from the FG construct
        :py:class: `plumbum.commands.modifiers.FG`
        """
        ...

    def run_tee(self, **kwargs):  # -> tuple[Any, LiteralString, LiteralString]:
        """
        Run this command using the TEE construct. Inherits all arguments from TEE
        :py:class: `plumbum.commands.modifiers.TEE`
        """
        ...

    def run_tf(self, **kwargs):  # -> bool:
        """
        Run this command using the TF construct. Inherits all arguments from TF
        :py:class: `plumbum.commands.modifiers.TF`
        """
        ...

    def run_retcode(self, **kwargs):
        """
        Run this command using the RETCODE construct. Inherits all arguments from RETCODE
        :py:class: `plumbum.commands.modifiers.RETCODE`
        """
        ...

    def run_nohup(self, **kwargs):
        """
        Run this command using the NOHUP construct. Inherits all arguments from NOHUP
        :py:class: `plumbum.commands.modifiers.NOHUP`
        """
        ...


class BoundCommand(BaseCommand):
    __slots__ = ...

    def __init__(self, cmd, args) -> None:
        ...

    def __repr__(self):  # -> str:
        ...

    def formulate(self, level=..., args=...):
        ...
    @property

    def machine(self):
        ...

    def popen(self, args=..., **kwargs):
        ...


class BoundEnvCommand(BaseCommand):
    __slots__ = ...

    def __init__(self, cmd, env=..., cwd=...) -> None:
        ...

    def __repr__(self):  # -> str:
        ...

    def formulate(self, level=..., args=...):
        ...
    @property

    def machine(self):
        ...

    def popen(self, args=..., cwd=..., env=..., **kwargs):
        ...


class Pipeline(BaseCommand):
    __slots__ = ...

    def __init__(self, srccmd, dstcmd) -> None:
        ...

    def __repr__(self):  # -> str:
        ...

    def formulate(self, level=..., args=...):  # -> list[Any | str]:
        ...

    @property

    def machine(self):
        ...

    def popen(self, args=..., **kwargs):
        ...


class BaseRedirection(BaseCommand):
    __slots__ = ...
    SYM: ClassVar[str]
    KWARG: ClassVar[str]
    MODE: ClassVar[str]

    def __init__(self, cmd, file) -> None:
        ...

    def __repr__(self):  # -> str:
        ...

    def formulate(self, level=..., args=...):  # -> list[Any | str]:
        ...

    @property

    def machine(self):
        ...

    def popen(self, args=..., **kwargs):
        ...


class StdinRedirection(BaseRedirection):
    __slots__ = ...
    SYM = ...
    KWARG = ...
    MODE = ...


class StdoutRedirection(BaseRedirection):
    __slots__ = ...
    SYM = ...
    KWARG = ...
    MODE = ...


class AppendingStdoutRedirection(BaseRedirection):
    __slots__ = ...
    SYM = ...
    KWARG = ...
    MODE = ...


class StderrRedirection(BaseRedirection):
    __slots__ = ...
    SYM = ...
    KWARG = ...
    MODE = ...


class _ERROUT(int):

    def __repr__(self):  # -> Literal['ERROUT']:
        ...

    def __str__(self) -> str:
        ...

ERROUT = ...


class StdinDataRedirection(BaseCommand):
    __slots__ = ...
    CHUNK_SIZE = ...

    def __init__(self, cmd, data) -> None:
        ...

    def formulate(self, level=..., args=...):  # -> list[str | Any]:
        ...

    @property

    def machine(self):
        ...

    def popen(self, args=..., **kwargs):
        ...


class ConcreteCommand(BaseCommand):
    __slots__ = ...
    QUOTE_LEVEL: ClassVar[int]

    def __init__(self, executable, encoding) -> None:
        ...

    def __str__(self) -> str:
        ...

    def __repr__(self):  # -> str:
        ...

    def formulate(self, level=..., args=...):  # -> list[str]:
        ...

    @property

    def machine(self):
        ...

    def popen(self, args=..., **kwargs):
        ...
