"""
This type stub file was generated by pyright.
"""


class _fake_lock:
    """Needed to allow normal os.exit() to work without error"""

    @staticmethod

    def acquire(_):  # -> Literal[True]:
        ...

    @staticmethod

    def release():  # -> None:
        ...


def posix_daemonize(command, cwd, stdout=..., stderr=..., append=...):  # -> Popen[Any]:
    ...


def win32_daemonize(command, cwd, stdout=..., stderr=..., append=...):
    ...
