"""
This type stub file was generated by pyright.
"""


from logging import DEBUG, INFO


class Future:
    """Represents a "future result" of a running process. It basically wraps a ``Popen``
    object and the expected exit code, and provides poll(), wait(), returncode, stdout,
    and stderr.
    """

    def __init__(self, proc, expected_retcode, timeout=...) -> None:
        ...

    def __repr__(self):  # -> str:
        ...

    def poll(self):  # -> bool:
        """Polls the underlying process for termination; returns ``False`` if still running,
        or ``True`` if terminated"""
        ...
    ready = ...

    def wait(self):  # -> None:
        """Waits for the process to terminate; will raise a
        :class:`plumbum.commands.ProcessExecutionError` in case of failure"""
        ...

    @property

    def stdout(self):  # -> str | bytes | None:
        """The process' stdout; accessing this property will wait for the process to finish"""
        ...

    @property

    def stderr(self):  # -> str | bytes | None:
        """The process' stderr; accessing this property will wait for the process to finish"""
        ...

    @property

    def returncode(self):  # -> None:
        """The process' returncode; accessing this property will wait for the process to finish"""
        ...


class ExecutionModifier:
    __slots__ = ...

    def __repr__(self):  # -> str:
        """Automatically creates a representation for given subclass with slots.
        Ignore hidden properties."""
        ...

    @classmethod

    def __call__(cls, *args, **kwargs):  # -> Self:
        ...


class _BG(ExecutionModifier):
    """
    An execution modifier that runs the given command in the background, returning a
    :class:`Future <plumbum.commands.Future>` object. In order to mimic shell syntax, it applies
    when you right-and it with a command. If you wish to expect a different return code
    (other than the normal success indicate by 0), use ``BG(retcode)``. Example::

        future = sleep[5] & BG       # a future expecting an exit code of 0
        future = sleep[5] & BG(7)    # a future expecting an exit code of 7

    .. note::

       When processes run in the **background** (either via ``popen`` or
       :class:`& BG <plumbum.commands.BG>`), their stdout/stderr pipes might fill up,
       causing them to hang. If you know a process produces output, be sure to consume it
       every once in a while, using a monitoring thread/reactor in the background.
       For more info, see `#48 <https://github.com/tomerfiliba/plumbum/issues/48>`_
    """

    __slots__ = ...

    def __init__(self, retcode=..., timeout=..., **kargs) -> None:
        ...

    def __rand__(self, cmd):  # -> Future:
        ...


class _FG(ExecutionModifier):
    """
    An execution modifier that runs the given command in the foreground, passing it the
    current process' stdin, stdout and stderr. Useful for interactive programs that require
    a TTY. There is no return value.

    In order to mimic shell syntax, it applies when you right-and it with a command.
    If you wish to expect a different return code (other than the normal success indicate by 0),
    use ``FG(retcode)``. Example::

        vim & FG       # run vim in the foreground, expecting an exit code of 0
        vim & FG(7)    # run vim in the foreground, expecting an exit code of 7
    """

    __slots__ = ...

    def __init__(self, retcode=..., timeout=...) -> None:
        ...

    def __rand__(self, cmd):  # -> None:
        ...


class _TEE(ExecutionModifier):
    """Run a command, dumping its stdout/stderr to the current process's stdout
    and stderr, but ALSO return them.  Useful for interactive programs that
    expect a TTY but also have valuable output.

    Use as:

        ls["-l"] & TEE

    Returns a tuple of (return code, stdout, stderr), just like ``run()``.
    """

    __slots__ = ...

    def __init__(self, retcode=..., buffered=..., timeout=...) -> None:
        """`retcode` is the return code to expect to mean "success".  Set
        `buffered` to False to disable line-buffering the output, which may
        cause stdout and stderr to become more entangled than usual.
        """
        ...

    def __rand__(self, cmd):  # -> tuple[Any, LiteralString, LiteralString]:
        ...


class _TF(ExecutionModifier):
    """
    An execution modifier that runs the given command, but returns True/False depending on the retcode.
    This returns True if the expected exit code is returned, and false if it is not.
    This is useful for checking true/false bash commands.

    If you wish to expect a different return code (other than the normal success indicate by 0),
    use ``TF(retcode)``. If you want to run the process in the foreground, then use
    ``TF(FG=True)``.

    Example::

        local['touch']['/root/test'] & TF * Returns False, since this cannot be touched
        local['touch']['/root/test'] & TF(1) # Returns True
        local['touch']['/root/test'] & TF(FG=True) * Returns False, will show error message
    """

    __slots__ = ...

    def __init__(self, retcode=..., FG=..., timeout=...) -> None:
        """`retcode` is the return code to expect to mean "success".  Set
        `FG` to True to run in the foreground.
        """
        ...

    @classmethod

    def __call__(cls, *args, **kwargs):  # -> Self:
        ...

    def __rand__(self, cmd):  # -> bool:
        ...


class _RETCODE(ExecutionModifier):
    """
    An execution modifier that runs the given command, causing it to run and return the retcode.
    This is useful for working with bash commands that have important retcodes but not very
    useful output.

    If you want to run the process in the foreground, then use ``RETCODE(FG=True)``.

    Example::

        local['touch']['/root/test'] & RETCODE # Returns 1, since this cannot be touched
        local['touch']['/root/test'] & RETCODE(FG=True) * Returns 1, will show error message
    """

    __slots__ = ...

    def __init__(self, FG=..., timeout=...) -> None:
        """`FG` to True to run in the foreground."""
        ...

    @classmethod

    def __call__(cls, *args, **kwargs):  # -> Self:
        ...

    def __rand__(self, cmd):
        ...


class _NOHUP(ExecutionModifier):
    """
    An execution modifier that runs the given command in the background, disconnected
    from the current process, returning a
    standard popen object. It will keep running even if you close the current process.
    In order to slightly mimic shell syntax, it applies
    when you right-and it with a command. If you wish to use a different working directory
    or different stdout, stderr, you can use named arguments. The default is ``NOHUP(
    cwd=local.cwd, stdout='nohup.out', stderr=None)``. If stderr is None, stderr will be
    sent to stdout. Use ``os.devnull`` for null output. Will respect redirected output.
    Example::

        sleep[5] & NOHUP                       # Outputs to nohup.out
        sleep[5] & NOHUP(stdout=os.devnull)    # No output

    The equivalent bash command would be

    .. code-block:: bash

        nohup sleep 5 &

    """

    __slots__ = ...

    def __init__(self, cwd=..., stdout=..., stderr=..., append=...) -> None:
        """Set ``cwd``, ``stdout``, or ``stderr``.
        Runs as a forked process. You can set ``append=False``, too.
        """
        ...

    def __rand__(self, cmd):
        ...


class LogPipe:

    def __init__(self, line_timeout, kw, levels, prefix, log) -> None:
        ...

    def __rand__(self, cmd):
        ...


class PipeToLoggerMixin:
    """
    This mixin allows piping plumbum commands' output into a logger.
    The logger must implement a ``log(level, msg)`` method, as in ``logging.Logger``

    Example::

        class MyLogger(logging.Logger, PipeToLoggerMixin):
            pass

        logger = MyLogger("example.app")

    Here we send the output of an install.sh script into our log::

        local['./install.sh'] & logger

    We can choose the log-level for each stream::

        local['./install.sh'] & logger.pipe(out_level=logging.DEBUG, err_level=logging.DEBUG)

    Or use a convenience method for it::

        local['./install.sh'] & logger.pipe_debug()

    A prefix can be added to each line::

        local['./install.sh'] & logger.pipe(prefix="install.sh: ")

    If the command fails, an exception is raised as usual. This can be modified::

        local['install.sh'] & logger.pipe_debug(retcode=None)

    An exception is also raised if too much time (``DEFAULT_LINE_TIMEOUT``) passed between lines in the stream,
    This can also be modified::

        local['install.sh'] & logger.pipe(line_timeout=10)

    If we happen to use logbook::

        class MyLogger(logbook.Logger, PipeToLoggerMixin):
            from logbook import DEBUG, INFO  # hook up with logbook's levels

    """

    DEFAULT_LINE_TIMEOUT = ...
    DEFAULT_STDOUT = ...
    DEFAULT_STDERR = ...
    INFO = ...
    DEBUG = ...

    def pipe(self, out_level=..., err_level=..., prefix=..., line_timeout=..., **kw):  # -> LogPipe:
        """
        Pipe a command's stdout and stderr lines into this logger.

        :param out_level: the log level for lines coming from stdout
        :param err_level: the log level for lines coming from stderr

        Optionally use `prefix` for each line.
        """
        ...

    def pipe_info(self, prefix=..., **kw):  # -> LogPipe:
        """
        Pipe a command's stdout and stderr lines into this logger (both at level INFO)
        """
        ...

    def pipe_debug(self, prefix=..., **kw):  # -> LogPipe:
        """
        Pipe a command's stdout and stderr lines into this logger (both at level DEBUG)
        """
        ...

    def __rand__(self, cmd):
        """
        Pipe a command's stdout and stderr lines into this logger.
        Log levels for each stream are determined by ``DEFAULT_STDOUT`` and ``DEFAULT_STDERR``.
        """
        ...

BG = ...
FG = ...
NOHUP = ...
RETCODE = ...
TEE = ...
TF = ...
