from typing import Any

class YandexTranslate:
    def __init__(self, key: str) -> None: ...
    def translate(self, text: str, lang: str) -> dict[str, Any]: ...
    def detect(self, text: str) -> str: ...
    def dirs(self) -> list[str]: ...
