"""
This type stub file was generated by pyright.
"""


from _typeshed import SupportsWrite
from typing import Any, Protocol
from typing_extensions import TypeAlias

Box: TypeAlias = tuple[tuple[int, int], tuple[int, int]]
Ink: TypeAlias = tuple[int, int, int] | tuple[int, int, int, int]
ErrorCorrect: TypeAlias = int
MaskPattern: TypeAlias = int


class Writeable(SupportsWrite[bytes], Protocol):

    def seek(self, offset: int, /) -> Any:
        ...
