# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bitmessageui.ui'
#
# Created: Fri Aug 01 15:30:14 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt6 import QtCore, QtGui, QtWidgets

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:

    def _fromUtf8(s):
        return s


try:
    _encoding = QtWidgets.QApplication.UnicodeUTF8

    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig, _encoding)

except AttributeError:

    def _translate(context, text, disambig):
        return QtWidgets.QApplication.translate(context, text, disambig)


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(885, 580)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/images/can-icon-24px.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.tabWidget.setFont(font)
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.TabPosition.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.TabShape.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.inbox = QtWidgets.QWidget()
        self.inbox.setObjectName("inbox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.inbox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayoutSearch = QtWidgets.QHBoxLayout()
        self.horizontalLayoutSearch.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayoutSearch.setObjectName("horizontalLayoutSearch")
        self.inboxSearchLineEdit = QtWidgets.QLineEdit(self.inbox)
        self.inboxSearchLineEdit.setObjectName("inboxSearchLineEdit")
        self.horizontalLayoutSearch.addWidget(self.inboxSearchLineEdit)
        self.inboxSearchOptionCB = QtWidgets.QComboBox(self.inbox)
        self.inboxSearchOptionCB.setObjectName("inboxSearchOptionCB")
        self.inboxSearchOptionCB.addItem(_fromUtf8(""))
        self.inboxSearchOptionCB.addItem(_fromUtf8(""))
        self.inboxSearchOptionCB.addItem(_fromUtf8(""))
        self.inboxSearchOptionCB.addItem(_fromUtf8(""))
        self.inboxSearchOptionCB.addItem(_fromUtf8(""))
        self.horizontalLayoutSearch.addWidget(self.inboxSearchOptionCB)
        self.verticalLayout_2.addLayout(self.horizontalLayoutSearch)
        self.splitter = QtWidgets.QSplitter(self.inbox)
        self.splitter.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter.setObjectName("splitter")
        self.tableWidgetInbox = QtWidgets.QTableWidget(self.splitter)
        self.tableWidgetInbox.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidgetInbox.setAlternatingRowColors(True)
        self.tableWidgetInbox.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.tableWidgetInbox.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidgetInbox.setWordWrap(False)
        self.tableWidgetInbox.setObjectName("tableWidgetInbox")
        self.tableWidgetInbox.setColumnCount(4)
        self.tableWidgetInbox.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInbox.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInbox.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInbox.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetInbox.setHorizontalHeaderItem(3, item)
        self.tableWidgetInbox.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetInbox.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidgetInbox.horizontalHeader().setHighlightSections(False)
        self.tableWidgetInbox.horizontalHeader().setMinimumSectionSize(27)
        self.tableWidgetInbox.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetInbox.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetInbox.verticalHeader().setVisible(False)
        self.tableWidgetInbox.verticalHeader().setDefaultSectionSize(26)
        self.textEditInboxMessage = QtWidgets.QTextEdit(self.splitter)
        self.textEditInboxMessage.setBaseSize(QtCore.QSize(0, 500))
        self.textEditInboxMessage.setReadOnly(True)
        self.textEditInboxMessage.setObjectName("textEditInboxMessage")
        self.verticalLayout_2.addWidget(self.splitter)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/images/inbox.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.inbox, icon1, _fromUtf8(""))
        self.send = QtWidgets.QWidget()
        self.send.setObjectName("send")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.send)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButtonLoadFromAddressBook = QtWidgets.QPushButton(self.send)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButtonLoadFromAddressBook.setFont(font)
        self.pushButtonLoadFromAddressBook.setObjectName("pushButtonLoadFromAddressBook")
        self.gridLayout_2.addWidget(self.pushButtonLoadFromAddressBook, 3, 2, 1, 1)
        self.pushButtonFetchNamecoinID = QtWidgets.QPushButton(self.send)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.pushButtonFetchNamecoinID.setFont(font)
        self.pushButtonFetchNamecoinID.setObjectName("pushButtonFetchNamecoinID")
        self.gridLayout_2.addWidget(self.pushButtonFetchNamecoinID, 3, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.send)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.comboBoxSendFrom = QtWidgets.QComboBox(self.send)
        self.comboBoxSendFrom.setMinimumSize(QtCore.QSize(300, 0))
        self.comboBoxSendFrom.setObjectName("comboBoxSendFrom")
        self.gridLayout_2.addWidget(self.comboBoxSendFrom, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.send)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.labelFrom = QtWidgets.QLabel(self.send)
        self.labelFrom.setText(_fromUtf8(""))
        self.labelFrom.setObjectName("labelFrom")
        self.gridLayout_2.addWidget(self.labelFrom, 2, 2, 1, 3)
        self.radioButtonSpecific = QtWidgets.QRadioButton(self.send)
        self.radioButtonSpecific.setChecked(True)
        self.radioButtonSpecific.setObjectName("radioButtonSpecific")
        self.gridLayout_2.addWidget(self.radioButtonSpecific, 0, 1, 1, 1)
        self.lineEditTo = QtWidgets.QLineEdit(self.send)
        self.lineEditTo.setObjectName("lineEditTo")
        self.gridLayout_2.addWidget(self.lineEditTo, 3, 1, 1, 1)
        self.textEditMessage = QtWidgets.QTextEdit(self.send)
        self.textEditMessage.setObjectName("textEditMessage")
        self.gridLayout_2.addWidget(self.textEditMessage, 5, 1, 2, 5)
        self.label = QtWidgets.QLabel(self.send)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.send)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 297, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 6, 0, 1, 1)
        self.radioButtonBroadcast = QtWidgets.QRadioButton(self.send)
        self.radioButtonBroadcast.setObjectName("radioButtonBroadcast")
        self.gridLayout_2.addWidget(self.radioButtonBroadcast, 1, 1, 1, 3)
        self.lineEditSubject = QtWidgets.QLineEdit(self.send)
        self.lineEditSubject.setText(_fromUtf8(""))
        self.lineEditSubject.setObjectName("lineEditSubject")
        self.gridLayout_2.addWidget(self.lineEditSubject, 4, 1, 1, 5)
        spacerItem1 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 3, 4, 1, 1)
        self.pushButtonSend = QtWidgets.QPushButton(self.send)
        self.pushButtonSend.setObjectName("pushButtonSend")
        self.gridLayout_2.addWidget(self.pushButtonSend, 7, 5, 1, 1)
        self.labelSendBroadcastWarning = QtWidgets.QLabel(self.send)
        self.labelSendBroadcastWarning.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Ignored, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelSendBroadcastWarning.sizePolicy().hasHeightForWidth())
        self.labelSendBroadcastWarning.setSizePolicy(sizePolicy)
        self.labelSendBroadcastWarning.setIndent(-1)
        self.labelSendBroadcastWarning.setObjectName("labelSendBroadcastWarning")
        self.gridLayout_2.addWidget(self.labelSendBroadcastWarning, 7, 1, 1, 4)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/newPrefix/images/send.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.send, icon2, _fromUtf8(""))
        self.sent = QtWidgets.QWidget()
        self.sent.setObjectName("sent")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.sent)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sentSearchLineEdit = QtWidgets.QLineEdit(self.sent)
        self.sentSearchLineEdit.setObjectName("sentSearchLineEdit")
        self.horizontalLayout.addWidget(self.sentSearchLineEdit)
        self.sentSearchOptionCB = QtWidgets.QComboBox(self.sent)
        self.sentSearchOptionCB.setObjectName("sentSearchOptionCB")
        self.sentSearchOptionCB.addItem(_fromUtf8(""))
        self.sentSearchOptionCB.addItem(_fromUtf8(""))
        self.sentSearchOptionCB.addItem(_fromUtf8(""))
        self.sentSearchOptionCB.addItem(_fromUtf8(""))
        self.sentSearchOptionCB.addItem(_fromUtf8(""))
        self.horizontalLayout.addWidget(self.sentSearchOptionCB)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter_2 = QtWidgets.QSplitter(self.sent)
        self.splitter_2.setOrientation(QtCore.Qt.Orientation.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.tableWidgetSent = QtWidgets.QTableWidget(self.splitter_2)
        self.tableWidgetSent.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidgetSent.setDragDropMode(QtWidgets.QAbstractItemView.DragDropMode.DragDrop)
        self.tableWidgetSent.setAlternatingRowColors(True)
        self.tableWidgetSent.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.tableWidgetSent.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidgetSent.setWordWrap(False)
        self.tableWidgetSent.setObjectName("tableWidgetSent")
        self.tableWidgetSent.setColumnCount(4)
        self.tableWidgetSent.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSent.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSent.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSent.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSent.setHorizontalHeaderItem(3, item)
        self.tableWidgetSent.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetSent.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidgetSent.horizontalHeader().setHighlightSections(False)
        self.tableWidgetSent.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetSent.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetSent.verticalHeader().setVisible(False)
        self.tableWidgetSent.verticalHeader().setStretchLastSection(False)
        self.textEditSentMessage = QtWidgets.QTextEdit(self.splitter_2)
        self.textEditSentMessage.setReadOnly(True)
        self.textEditSentMessage.setObjectName("textEditSentMessage")
        self.verticalLayout.addWidget(self.splitter_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/newPrefix/images/sent.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.sent, icon3, _fromUtf8(""))
        self.youridentities = QtWidgets.QWidget()
        self.youridentities.setObjectName("youridentities")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.youridentities)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButtonNewAddress = QtWidgets.QPushButton(self.youridentities)
        self.pushButtonNewAddress.setObjectName("pushButtonNewAddress")
        self.gridLayout_3.addWidget(self.pushButtonNewAddress, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(689, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 1, 1, 1)
        self.tableWidgetYourIdentities = QtWidgets.QTableWidget(self.youridentities)
        self.tableWidgetYourIdentities.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.tableWidgetYourIdentities.setLineWidth(1)
        self.tableWidgetYourIdentities.setAlternatingRowColors(True)
        self.tableWidgetYourIdentities.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableWidgetYourIdentities.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidgetYourIdentities.setObjectName("tableWidgetYourIdentities")
        self.tableWidgetYourIdentities.setColumnCount(3)
        self.tableWidgetYourIdentities.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setKerning(True)
        item.setFont(font)
        self.tableWidgetYourIdentities.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetYourIdentities.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetYourIdentities.setHorizontalHeaderItem(2, item)
        self.tableWidgetYourIdentities.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetYourIdentities.horizontalHeader().setDefaultSectionSize(346)
        self.tableWidgetYourIdentities.horizontalHeader().setMinimumSectionSize(52)
        self.tableWidgetYourIdentities.horizontalHeader().setSortIndicatorShown(True)
        self.tableWidgetYourIdentities.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetYourIdentities.verticalHeader().setVisible(False)
        self.tableWidgetYourIdentities.verticalHeader().setDefaultSectionSize(26)
        self.tableWidgetYourIdentities.verticalHeader().setSortIndicatorShown(False)
        self.tableWidgetYourIdentities.verticalHeader().setStretchLastSection(False)
        self.gridLayout_3.addWidget(self.tableWidgetYourIdentities, 1, 0, 1, 2)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/newPrefix/images/identities.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.youridentities, icon4, _fromUtf8(""))
        self.subscriptions = QtWidgets.QWidget()
        self.subscriptions.setObjectName("subscriptions")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.subscriptions)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_5 = QtWidgets.QLabel(self.subscriptions)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 2)
        self.pushButtonAddSubscription = QtWidgets.QPushButton(self.subscriptions)
        self.pushButtonAddSubscription.setObjectName("pushButtonAddSubscription")
        self.gridLayout_4.addWidget(self.pushButtonAddSubscription, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(689, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 1, 1, 1)
        self.tableWidgetSubscriptions = QtWidgets.QTableWidget(self.subscriptions)
        self.tableWidgetSubscriptions.setAlternatingRowColors(True)
        self.tableWidgetSubscriptions.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableWidgetSubscriptions.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidgetSubscriptions.setObjectName("tableWidgetSubscriptions")
        self.tableWidgetSubscriptions.setColumnCount(2)
        self.tableWidgetSubscriptions.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSubscriptions.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetSubscriptions.setHorizontalHeaderItem(1, item)
        self.tableWidgetSubscriptions.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetSubscriptions.horizontalHeader().setDefaultSectionSize(400)
        self.tableWidgetSubscriptions.horizontalHeader().setHighlightSections(False)
        self.tableWidgetSubscriptions.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetSubscriptions.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetSubscriptions.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.tableWidgetSubscriptions, 2, 0, 1, 2)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/newPrefix/images/subscriptions.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.subscriptions, icon5, _fromUtf8(""))
        self.addressbook = QtWidgets.QWidget()
        self.addressbook.setObjectName("addressbook")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.addressbook)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_6 = QtWidgets.QLabel(self.addressbook)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 2)
        self.pushButtonAddAddressBook = QtWidgets.QPushButton(self.addressbook)
        self.pushButtonAddAddressBook.setObjectName("pushButtonAddAddressBook")
        self.gridLayout_5.addWidget(self.pushButtonAddAddressBook, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(689, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_5.addItem(spacerItem4, 1, 1, 1, 1)
        self.tableWidgetAddressBook = QtWidgets.QTableWidget(self.addressbook)
        self.tableWidgetAddressBook.setAlternatingRowColors(True)
        self.tableWidgetAddressBook.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.ExtendedSelection)
        self.tableWidgetAddressBook.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidgetAddressBook.setObjectName("tableWidgetAddressBook")
        self.tableWidgetAddressBook.setColumnCount(2)
        self.tableWidgetAddressBook.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAddressBook.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetAddressBook.setHorizontalHeaderItem(1, item)
        self.tableWidgetAddressBook.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetAddressBook.horizontalHeader().setDefaultSectionSize(400)
        self.tableWidgetAddressBook.horizontalHeader().setHighlightSections(False)
        self.tableWidgetAddressBook.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetAddressBook.verticalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.tableWidgetAddressBook, 2, 0, 1, 2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/newPrefix/images/addressbook.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.addressbook, icon6, _fromUtf8(""))
        self.blackwhitelist = QtWidgets.QWidget()
        self.blackwhitelist.setObjectName("blackwhitelist")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.blackwhitelist)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.radioButtonBlacklist = QtWidgets.QRadioButton(self.blackwhitelist)
        self.radioButtonBlacklist.setChecked(True)
        self.radioButtonBlacklist.setObjectName("radioButtonBlacklist")
        self.gridLayout_6.addWidget(self.radioButtonBlacklist, 0, 0, 1, 2)
        self.radioButtonWhitelist = QtWidgets.QRadioButton(self.blackwhitelist)
        self.radioButtonWhitelist.setObjectName("radioButtonWhitelist")
        self.gridLayout_6.addWidget(self.radioButtonWhitelist, 1, 0, 1, 2)
        self.pushButtonAddBlacklist = QtWidgets.QPushButton(self.blackwhitelist)
        self.pushButtonAddBlacklist.setObjectName("pushButtonAddBlacklist")
        self.gridLayout_6.addWidget(self.pushButtonAddBlacklist, 2, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(689, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout_6.addItem(spacerItem5, 2, 1, 1, 1)
        self.tableWidgetBlacklist = QtWidgets.QTableWidget(self.blackwhitelist)
        self.tableWidgetBlacklist.setAlternatingRowColors(True)
        self.tableWidgetBlacklist.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableWidgetBlacklist.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidgetBlacklist.setObjectName("tableWidgetBlacklist")
        self.tableWidgetBlacklist.setColumnCount(2)
        self.tableWidgetBlacklist.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBlacklist.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetBlacklist.setHorizontalHeaderItem(1, item)
        self.tableWidgetBlacklist.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetBlacklist.horizontalHeader().setDefaultSectionSize(400)
        self.tableWidgetBlacklist.horizontalHeader().setHighlightSections(False)
        self.tableWidgetBlacklist.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidgetBlacklist.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetBlacklist.verticalHeader().setVisible(False)
        self.gridLayout_6.addWidget(self.tableWidgetBlacklist, 3, 0, 1, 2)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/newPrefix/images/blacklist.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.blackwhitelist, icon7, _fromUtf8(""))
        self.networkstatus = QtWidgets.QWidget()
        self.networkstatus.setObjectName("networkstatus")
        self.pushButtonStatusIcon = QtWidgets.QPushButton(self.networkstatus)
        self.pushButtonStatusIcon.setGeometry(QtCore.QRect(680, 440, 21, 23))
        self.pushButtonStatusIcon.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/newPrefix/images/redicon.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButtonStatusIcon.setIcon(icon8)
        self.pushButtonStatusIcon.setFlat(True)
        self.pushButtonStatusIcon.setObjectName("pushButtonStatusIcon")
        self.tableWidgetConnectionCount = QtWidgets.QTableWidget(self.networkstatus)
        self.tableWidgetConnectionCount.setGeometry(QtCore.QRect(20, 70, 241, 241))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(212, 208, 200))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        self.tableWidgetConnectionCount.setPalette(palette)
        self.tableWidgetConnectionCount.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.tableWidgetConnectionCount.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.tableWidgetConnectionCount.setProperty("showDropIndicator", False)
        self.tableWidgetConnectionCount.setAlternatingRowColors(True)
        self.tableWidgetConnectionCount.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.tableWidgetConnectionCount.setObjectName("tableWidgetConnectionCount")
        self.tableWidgetConnectionCount.setColumnCount(2)
        self.tableWidgetConnectionCount.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetConnectionCount.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidgetConnectionCount.setHorizontalHeaderItem(1, item)
        self.tableWidgetConnectionCount.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidgetConnectionCount.horizontalHeader().setHighlightSections(False)
        self.tableWidgetConnectionCount.horizontalHeader().setStretchLastSection(True)
        self.tableWidgetConnectionCount.verticalHeader().setVisible(False)
        self.labelTotalConnections = QtWidgets.QLabel(self.networkstatus)
        self.labelTotalConnections.setGeometry(QtCore.QRect(20, 30, 401, 16))
        self.labelTotalConnections.setObjectName("labelTotalConnections")
        self.labelStartupTime = QtWidgets.QLabel(self.networkstatus)
        self.labelStartupTime.setGeometry(QtCore.QRect(320, 110, 331, 20))
        self.labelStartupTime.setObjectName("labelStartupTime")
        self.labelMessageCount = QtWidgets.QLabel(self.networkstatus)
        self.labelMessageCount.setGeometry(QtCore.QRect(350, 130, 361, 16))
        self.labelMessageCount.setObjectName("labelMessageCount")
        self.labelPubkeyCount = QtWidgets.QLabel(self.networkstatus)
        self.labelPubkeyCount.setGeometry(QtCore.QRect(350, 170, 331, 16))
        self.labelPubkeyCount.setObjectName("labelPubkeyCount")
        self.labelBroadcastCount = QtWidgets.QLabel(self.networkstatus)
        self.labelBroadcastCount.setGeometry(QtCore.QRect(350, 150, 351, 16))
        self.labelBroadcastCount.setObjectName("labelBroadcastCount")
        self.labelLookupsPerSecond = QtWidgets.QLabel(self.networkstatus)
        self.labelLookupsPerSecond.setGeometry(QtCore.QRect(320, 250, 291, 16))
        self.labelLookupsPerSecond.setObjectName("labelLookupsPerSecond")
        self.labelBytesRecvCount = QtWidgets.QLabel(self.networkstatus)
        self.labelBytesRecvCount.setGeometry(QtCore.QRect(350, 210, 251, 16))
        self.labelBytesRecvCount.setObjectName("labelBytesRecvCount")
        self.labelBytesSentCount = QtWidgets.QLabel(self.networkstatus)
        self.labelBytesSentCount.setGeometry(QtCore.QRect(350, 230, 251, 16))
        self.labelBytesSentCount.setObjectName("labelBytesSentCount")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/newPrefix/images/networkstatus.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.tabWidget.addTab(self.networkstatus, icon9, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 885, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setMaximumSize(QtCore.QSize(16777215, 22))
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionImport_keys = QtGui.QAction(MainWindow)
        self.actionImport_keys.setObjectName("actionImport_keys")
        self.actionManageKeys = QtGui.QAction(MainWindow)
        self.actionManageKeys.setCheckable(False)
        self.actionManageKeys.setEnabled(True)
        icon = QtGui.QIcon.fromTheme("dialog-password")
        self.actionManageKeys.setIcon(icon)
        self.actionManageKeys.setObjectName("actionManageKeys")
        self.actionExit = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("application-exit")
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.actionHelp = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("help-contents")
        self.actionHelp.setIcon(icon)
        self.actionHelp.setObjectName("actionHelp")
        self.actionAbout = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("help-about")
        self.actionAbout.setIcon(icon)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSettings = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("document-properties")
        self.actionSettings.setIcon(icon)
        self.actionSettings.setObjectName("actionSettings")
        self.actionRegenerateDeterministicAddresses = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("view-refresh")
        self.actionRegenerateDeterministicAddresses.setIcon(icon)
        self.actionRegenerateDeterministicAddresses.setObjectName("actionRegenerateDeterministicAddresses")
        self.actionDeleteAllTrashedMessages = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("user-trash")
        self.actionDeleteAllTrashedMessages.setIcon(icon)
        self.actionDeleteAllTrashedMessages.setObjectName("actionDeleteAllTrashedMessages")
        self.actionJoinChan = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon.fromTheme("contact-new")
        self.actionJoinChan.setIcon(icon)
        self.actionJoinChan.setObjectName("actionJoinChan")
        self.menuFile.addAction(self.actionManageKeys)
        self.menuFile.addAction(self.actionDeleteAllTrashedMessages)
        self.menuFile.addAction(self.actionRegenerateDeterministicAddresses)
        self.menuFile.addAction(self.actionJoinChan)
        self.menuFile.addAction(self.actionExit)
        self.menuSettings.addAction(self.actionSettings)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.radioButtonSpecific.toggled.connect(self.lineEditTo.setEnabled)
        self.radioButtonSpecific.clicked.connect(self.labelSendBroadcastWarning.hide)
        self.radioButtonBroadcast.clicked.connect(self.labelSendBroadcastWarning.show)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.tableWidgetInbox)
        MainWindow.setTabOrder(self.tableWidgetInbox, self.textEditInboxMessage)
        MainWindow.setTabOrder(self.textEditInboxMessage, self.radioButtonSpecific)
        MainWindow.setTabOrder(self.radioButtonSpecific, self.radioButtonBroadcast)
        MainWindow.setTabOrder(self.radioButtonBroadcast, self.comboBoxSendFrom)
        MainWindow.setTabOrder(self.comboBoxSendFrom, self.lineEditTo)
        MainWindow.setTabOrder(self.lineEditTo, self.pushButtonLoadFromAddressBook)
        MainWindow.setTabOrder(self.pushButtonLoadFromAddressBook, self.lineEditSubject)
        MainWindow.setTabOrder(self.lineEditSubject, self.textEditMessage)
        MainWindow.setTabOrder(self.textEditMessage, self.pushButtonSend)
        MainWindow.setTabOrder(self.pushButtonSend, self.tableWidgetSent)
        MainWindow.setTabOrder(self.tableWidgetSent, self.textEditSentMessage)
        MainWindow.setTabOrder(self.textEditSentMessage, self.pushButtonNewAddress)
        MainWindow.setTabOrder(self.pushButtonNewAddress, self.tableWidgetYourIdentities)
        MainWindow.setTabOrder(self.tableWidgetYourIdentities, self.pushButtonAddSubscription)
        MainWindow.setTabOrder(self.pushButtonAddSubscription, self.tableWidgetSubscriptions)
        MainWindow.setTabOrder(self.tableWidgetSubscriptions, self.pushButtonAddAddressBook)
        MainWindow.setTabOrder(self.pushButtonAddAddressBook, self.tableWidgetAddressBook)
        MainWindow.setTabOrder(self.tableWidgetAddressBook, self.radioButtonBlacklist)
        MainWindow.setTabOrder(self.radioButtonBlacklist, self.radioButtonWhitelist)
        MainWindow.setTabOrder(self.radioButtonWhitelist, self.pushButtonAddBlacklist)
        MainWindow.setTabOrder(self.pushButtonAddBlacklist, self.tableWidgetBlacklist)
        MainWindow.setTabOrder(self.tableWidgetBlacklist, self.tableWidgetConnectionCount)
        MainWindow.setTabOrder(self.tableWidgetConnectionCount, self.pushButtonStatusIcon)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Bitmessage", None))
        self.inboxSearchLineEdit.setPlaceholderText(_translate("MainWindow", "Search", None))
        self.inboxSearchOptionCB.setItemText(0, _translate("MainWindow", "All", None))
        self.inboxSearchOptionCB.setItemText(1, _translate("MainWindow", "To", None))
        self.inboxSearchOptionCB.setItemText(2, _translate("MainWindow", "From", None))
        self.inboxSearchOptionCB.setItemText(3, _translate("MainWindow", "Subject", None))
        self.inboxSearchOptionCB.setItemText(4, _translate("MainWindow", "Message", None))
        self.tableWidgetInbox.setSortingEnabled(True)
        item = self.tableWidgetInbox.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "To", None))
        item = self.tableWidgetInbox.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "From", None))
        item = self.tableWidgetInbox.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Subject", None))
        item = self.tableWidgetInbox.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Received", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.inbox), _translate("MainWindow", "Inbox", None))
        self.pushButtonLoadFromAddressBook.setText(_translate("MainWindow", "Load from Address book", None))
        self.pushButtonFetchNamecoinID.setText(_translate("MainWindow", "Fetch Namecoin ID", None))
        self.label_4.setText(_translate("MainWindow", "Message:", None))
        self.label_3.setText(_translate("MainWindow", "Subject:", None))
        self.radioButtonSpecific.setText(_translate("MainWindow", "Send to one or more specific people", None))
        self.textEditMessage.setHtml(
            _translate(
                "MainWindow",
                '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">\n'
                '<html><head><meta name="qrichtext" content="1" /><style type="text/css">\n'
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:'MS Shell Dlg 2'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
                '<p style="-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;"><br /></p></body></html>',
                None,
            )
        )
        self.label.setText(_translate("MainWindow", "To:", None))
        self.label_2.setText(_translate("MainWindow", "From:", None))
        self.radioButtonBroadcast.setText(_translate("MainWindow", "Broadcast to everyone who is subscribed to your address", None))
        self.pushButtonSend.setText(_translate("MainWindow", "Send", None))
        self.labelSendBroadcastWarning.setText(
            _translate(
                "MainWindow",
                "Be aware that broadcasts are only encrypted with your address. Anyone who knows your address can read them.",
                None,
            )
        )
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.send), _translate("MainWindow", "Send", None))
        self.sentSearchLineEdit.setPlaceholderText(_translate("MainWindow", "Search", None))
        self.sentSearchOptionCB.setItemText(0, _translate("MainWindow", "All", None))
        self.sentSearchOptionCB.setItemText(1, _translate("MainWindow", "To", None))
        self.sentSearchOptionCB.setItemText(2, _translate("MainWindow", "From", None))
        self.sentSearchOptionCB.setItemText(3, _translate("MainWindow", "Subject", None))
        self.sentSearchOptionCB.setItemText(4, _translate("MainWindow", "Message", None))
        self.tableWidgetSent.setSortingEnabled(True)
        item = self.tableWidgetSent.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "To", None))
        item = self.tableWidgetSent.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "From", None))
        item = self.tableWidgetSent.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Subject", None))
        item = self.tableWidgetSent.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Status", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.sent), _translate("MainWindow", "Sent", None))
        self.pushButtonNewAddress.setText(_translate("MainWindow", "New", None))
        self.tableWidgetYourIdentities.setSortingEnabled(True)
        item = self.tableWidgetYourIdentities.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Label (not shown to anyone)", None))
        item = self.tableWidgetYourIdentities.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Address", None))
        item = self.tableWidgetYourIdentities.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Stream", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.youridentities), _translate("MainWindow", "Your Identities", None))
        self.label_5.setText(
            _translate(
                "MainWindow",
                "Here you can subscribe to 'broadcast messages' that are sent by other users. Messages will appear in your Inbox. Addresses here override those on the Blacklist tab.",
                None,
            )
        )
        self.pushButtonAddSubscription.setText(_translate("MainWindow", "Add new Subscription", None))
        self.tableWidgetSubscriptions.setSortingEnabled(True)
        item = self.tableWidgetSubscriptions.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Label", None))
        item = self.tableWidgetSubscriptions.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Address", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.subscriptions), _translate("MainWindow", "Subscriptions", None))
        self.label_6.setText(
            _translate(
                "MainWindow",
                "The Address book is useful for adding names or labels to other people's Bitmessage addresses so that you can recognize them more easily in your inbox. You can add entries here using the 'Add' button, or from your inbox by right-clicking on a message.",
                None,
            )
        )
        self.pushButtonAddAddressBook.setText(_translate("MainWindow", "Add new entry", None))
        self.tableWidgetAddressBook.setSortingEnabled(True)
        item = self.tableWidgetAddressBook.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name or Label", None))
        item = self.tableWidgetAddressBook.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Address", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.addressbook), _translate("MainWindow", "Address Book", None))
        self.radioButtonBlacklist.setText(_translate("MainWindow", "Use a Blacklist (Allow all incoming messages except those on the Blacklist)", None))
        self.radioButtonWhitelist.setText(_translate("MainWindow", "Use a Whitelist (Block all incoming messages except those on the Whitelist)", None))
        self.pushButtonAddBlacklist.setText(_translate("MainWindow", "Add new entry", None))
        self.tableWidgetBlacklist.setSortingEnabled(True)
        item = self.tableWidgetBlacklist.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name or Label", None))
        item = self.tableWidgetBlacklist.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Address", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.blackwhitelist), _translate("MainWindow", "Blacklist", None))
        item = self.tableWidgetConnectionCount.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Stream #", None))
        item = self.tableWidgetConnectionCount.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Connections", None))
        self.labelTotalConnections.setText(_translate("MainWindow", "Total connections: 0", None))
        self.labelStartupTime.setText(_translate("MainWindow", "Since startup at asdf:", None))
        self.labelMessageCount.setText(_translate("MainWindow", "Processed 0 person-to-person message.", None))
        self.labelPubkeyCount.setText(_translate("MainWindow", "Processed 0 public key.", None))
        self.labelBroadcastCount.setText(_translate("MainWindow", "Processed 0 broadcast.", None))
        self.labelLookupsPerSecond.setText(_translate("MainWindow", "Inventory lookups per second: 0", None))
        self.labelBytesRecvCount.setText(_translate("MainWindow", "Down: 0 KB/s", None))
        self.labelBytesSentCount.setText(_translate("MainWindow", "Up: 0 KB/s", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.networkstatus), _translate("MainWindow", "Network Status", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionImport_keys.setText(_translate("MainWindow", "Import keys", None))
        self.actionManageKeys.setText(_translate("MainWindow", "Manage keys", None))
        self.actionExit.setText(_translate("MainWindow", "Quit", None))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.actionHelp.setShortcut(_translate("MainWindow", "F1", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionSettings.setText(_translate("MainWindow", "Settings", None))
        self.actionRegenerateDeterministicAddresses.setText(_translate("MainWindow", "Regenerate deterministic addresses", None))
        self.actionDeleteAllTrashedMessages.setText(_translate("MainWindow", "Delete all trashed messages", None))
        self.actionJoinChan.setText(_translate("MainWindow", "Join / Create chan", None))


from . import bitmessage_icons_rc
