"""
This type stub file was generated by pyright.
"""


class PopenAddons:
    """This adds a verify to popen objects to that the correct command is attributed when
    an error is thrown."""

    def verify(self, retcode, timeout, stdout, stderr):  # -> None:
        """This verifies that the correct command is attributed."""
        ...


class BaseMachine:
    """This is a base class for other machines. It contains common code to
    all machines in Plumbum."""

    def get(self, cmd, *othercommands):
        """This works a little like the ``.get`` method with dict's, only
        it supports an unlimited number of arguments, since later arguments
        are tried as commands and could also fail. It
        will try to call the first command, and if that is not found,
        it will call the next, etc. Will raise if no file named for the
        executable if a path is given, unlike ``[]`` access.

        Usage::

            best_zip = local.get('pigz','gzip')
        """
        ...

    def __contains__(self, cmd):  # -> bool:
        """Tests for the existence of the command, e.g., ``"ls" in plumbum.local``.
        ``cmd`` can be anything acceptable by ``__getitem__``.
        """
        ...

    @property

    def encoding(self):
        "This is a wrapper for custom_encoding"
        ...

    @encoding.setter

    def encoding(self, value):  # -> None:
        ...

    def daemonic_popen(self, command, cwd=..., stdout=..., stderr=..., append=...):
        ...

    class Cmd:

        def __init__(self, machine) -> None:
            ...

        def __getattr__(self, name):
            ...

    @property

    def cmd(self):  # -> Cmd:
        ...

    def clear_program_cache(self):  # -> None:
        """
        Clear the program cache, which is populated via ``machine.which(progname)`` calls.

        This cache speeds up the lookup of a program in the machines PATH, and is particularly
        effective for RemoteMachines.
        """
        ...
