"""
This type stub file was generated by pyright.
"""


from contextlib import contextmanager
from plumbum.commands import ConcreteCommand
from plumbum.commands.processes import iter_lines
from plumbum.lib import IS_WIN32
from plumbum.machines.base import BaseMachine, PopenAddons
from plumbum.machines.env import BaseEnv
from plumbum.path.local import LocalPath


class PlumbumLocalPopen(PopenAddons):
    iter_lines = ...

    def __init__(self, *args, **kwargs) -> None:
        ...

    def __iter__(self):  # -> Generator[tuple[None, ...] | tuple[Any, Any], Any, None]:
        ...

    def __enter__(self):  # -> Popen[str]:
        ...

    def __exit__(self, *args, **kwargs):  # -> None:
        ...

    def __getattr__(self, name):  # -> Any:
        ...


if IS_WIN32:
    ...
logger = ...


class LocalEnv(BaseEnv):
    """The local machine's environment; exposes a dict-like interface"""

    __slots__ = ...
    CASE_SENSITIVE = ...

    def __init__(self) -> None:
        ...

    def expand(self, expr):
        """Expands any environment variables and home shortcuts found in ``expr``
        (like ``os.path.expanduser`` combined with ``os.path.expandvars``)

        :param expr: An expression containing environment variables (as ``$FOO``) or
                     home shortcuts (as ``~/.bashrc``)

        :returns: The expanded string"""
        ...

    def expanduser(self, expr):
        """Expand home shortcuts (e.g., ``~/foo/bar`` or ``~john/foo/bar``)

        :param expr: An expression containing home shortcuts

        :returns: The expanded string"""
        ...


class LocalCommand(ConcreteCommand):
    __slots__ = ...
    QUOTE_LEVEL = ...

    def __init__(self, executable, encoding=...) -> None:
        ...
    @property

    def machine(self):  # -> LocalMachine:
        ...

    def popen(self, args=..., cwd=..., env=..., **kwargs):  # -> PlumbumLocalPopen:
        ...


class LocalMachine(BaseMachine):
    """The *local machine* (a singleton object). It serves as an entry point to everything
    related to the local machine, such as working directory and environment manipulation,
    command creation, etc.

    Attributes:

    * ``cwd`` - the local working directory
    * ``env`` - the local environment
    * ``custom_encoding`` - the local machine's default encoding (``sys.getfilesystemencoding()``)
    """

    cwd = ...
    env = ...
    custom_encoding = ...
    uname = ...
    _program_cache: dict[tuple[str, str], LocalPath] = ...

    def __init__(self) -> None:
        ...

    if IS_WIN32:
        _EXTENSIONS = ...
    else:
        ...

    @classmethod

    def which(cls, progname):  # -> LocalPath:
        """Looks up a program in the ``PATH``. If the program is not found, raises
        :class:`CommandNotFound <plumbum.commands.CommandNotFound>`

        :param progname: The program's name. Note that if underscores (``_``) are present
                         in the name, and the exact name is not found, they will be replaced
                         in turn by hyphens (``-``) then periods (``.``), and the name will
                         be looked up again for each alternative

        :returns: A :class:`LocalPath <plumbum.machines.local.LocalPath>`
        """
        ...

    def path(self, *parts):  # -> LocalPath:
        """A factory for :class:`LocalPaths <plumbum.path.local.LocalPath>`.
        Usage: ``p = local.path("/usr", "lib", "python2.7")``
        """
        ...

    def __contains__(self, cmd):  # -> bool:
        ...

    def __getitem__(self, cmd):  # -> LocalCommand:
        """Returns a `Command` object representing the given program. ``cmd`` can be a string or
        a :class:`LocalPath <plumbum.path.local.LocalPath>`; if it is a path, a command
        representing this path will be returned; otherwise, the program name will be looked up
        in the system's ``PATH`` (using ``which``). Usage::

            ls = local["ls"]
        """
        ...

    def daemonic_popen(self, command, cwd=..., stdout=..., stderr=..., append=...):  # -> Popen[Any]:
        """
        On POSIX systems:

        Run ``command`` as a UNIX daemon: fork a child process to setpid, redirect std handles to /dev/null,
        umask, close all fds, chdir to ``cwd``, then fork and exec ``command``. Returns a ``Popen`` process that
        can be used to poll/wait for the executed command (but keep in mind that you cannot access std handles)

        On Windows:

        Run ``command`` as a "Windows daemon": detach from controlling console and create a new process group.
        This means that the command will not receive console events and would survive its parent's termination.
        Returns a ``Popen`` object.

        .. note:: this does not run ``command`` as a system service, only detaches it from its parent.

        .. versionadded:: 1.3
        """
        ...
    if IS_WIN32:

        def list_processes(self):  # -> Generator[ProcInfo, Any, None]:
            """
            Returns information about all running processes (on Windows: using ``tasklist``)

            .. versionadded:: 1.3
            """
            ...
    else:

        def list_processes(self):  # -> Generator[ProcInfo, Any, None]:
            """
            Returns information about all running processes (on POSIX systems: using ``ps``)

            .. versionadded:: 1.3
            """
            ...

    def pgrep(self, pattern):  # -> Generator[ProcInfo, Any, None]:
        """
        Process grep: return information about all processes whose command-line args match the given regex pattern
        """
        ...

    def session(self, new_session=...):  # -> ShellSession:
        """Creates a new :class:`ShellSession <plumbum.session.ShellSession>` object; this
        invokes ``/bin/sh`` and executes commands on it over stdin/stdout/stderr"""
        ...

    @contextmanager

    def tempdir(self):  # -> Generator[LocalPath, Any, None]:
        """A context manager that creates a temporary directory, which is removed when the context
        exits"""
        ...

    @contextmanager

    def as_user(self, username=...):  # -> Generator[None, Any, None]:
        """Run nested commands as the given user. For example::

            head = local["head"]
            head("-n1", "/dev/sda1")    # this will fail...
            with local.as_user():
                head("-n1", "/dev/sda1")

        :param username: The user to run commands as. If not given, root (or Administrator) is assumed
        """
        ...

    def as_root(self):  # -> _GeneratorContextManager[None, None, None]:
        """A shorthand for :func:`as_user("root") <plumbum.machines.local.LocalMachine.as_user>`"""
        ...
    python = ...

local = ...
