"""
This type stub file was generated by pyright.
"""


import contextlib
from plumbum.commands import ConcreteCommand
from plumbum.machines.base import BaseMachine
from plumbum.machines.env import BaseEnv


class RemoteEnv(BaseEnv):
    """The remote machine's environment; exposes a dict-like interface"""

    __slots__ = ...

    def __init__(self, remote) -> None:
        ...

    def __delitem__(self, name):  # -> None:
        ...

    def __setitem__(self, name, value):  # -> None:
        ...

    def pop(self, name, *default):  # -> None:
        ...

    def update(self, *args, **kwargs):  # -> None:
        ...

    def expand(self, expr):
        """Expands any environment variables and home shortcuts found in ``expr``
        (like ``os.path.expanduser`` combined with ``os.path.expandvars``)

        :param expr: An expression containing environment variables (as ``$FOO``) or
                     home shortcuts (as ``~/.bashrc``)

        :returns: The expanded string"""
        ...

    def expanduser(self, expr):
        """Expand home shortcuts (e.g., ``~/foo/bar`` or ``~john/foo/bar``)

        :param expr: An expression containing home shortcuts

        :returns: The expanded string"""
        ...

    def getdelta(self):  # -> dict[Any, Any]:
        """Returns the difference between the this environment and the original environment of
        the remote machine"""
        ...


class RemoteCommand(ConcreteCommand):
    __slots__ = ...
    QUOTE_LEVEL = ...

    def __init__(self, remote, executable, encoding=...) -> None:
        ...
    @property

    def machine(self):  # -> Any:
        ...

    def __repr__(self):  # -> str:
        ...

    def popen(self, args=..., **kwargs):
        ...

    def nohup(self, cwd=..., stdout=..., stderr=..., append=...):
        """Runs a command detached."""
        ...


class ClosedRemoteMachine(Exception):
    ...


class ClosedRemote:
    __slots__ = ...

    def __init__(self, obj) -> None:
        ...

    def close(self):  # -> None:
        ...

    def __getattr__(self, name):
        ...


class BaseRemoteMachine(BaseMachine):
    """Represents a *remote machine*; serves as an entry point to everything related to that
    remote machine, such as working directory and environment manipulation, command creation,
    etc.

    Attributes:

    * ``cwd`` - the remote working directory
    * ``env`` - the remote environment
    * ``custom_encoding`` - the remote machine's default encoding (assumed to be UTF8)
    * ``connect_timeout`` - the connection timeout

    There also is a _cwd attribute that exists if the cwd is not current (del if cwd is changed).
    """

    RemoteCommand = RemoteCommand
    @property

    def cwd(self):  # -> RemoteWorkdir:
        ...

    def __init__(self, encoding=..., connect_timeout=..., new_session=...) -> None:
        ...

    def __repr__(self):  # -> str:
        ...

    def __enter__(self):  # -> Self:
        ...

    def __exit__(self, t, v, tb):  # -> None:
        ...

    def close(self):  # -> None:
        """closes the connection to the remote machine; all paths and programs will
        become defunct"""
        ...

    def path(self, *parts):  # -> RemotePath:
        """A factory for :class:`RemotePaths <plumbum.path.remote.RemotePath>`.
        Usage: ``p = rem.path("/usr", "lib", "python2.7")``
        """
        ...

    def which(self, progname):
        """Looks up a program in the ``PATH``. If the program is not found, raises
        :class:`CommandNotFound <plumbum.commands.CommandNotFound>`

        :param progname: The program's name. Note that if underscores (``_``) are present
                         in the name, and the exact name is not found, they will be replaced
                         in turn by hyphens (``-``) then periods (``.``), and the name will
                         be looked up again for each alternative

        :returns: A :class:`RemotePath <plumbum.path.local.RemotePath>`
        """
        ...

    def __getitem__(self, cmd):  # -> RemoteCommand:
        """Returns a `Command` object representing the given program. ``cmd`` can be a string or
        a :class:`RemotePath <plumbum.path.remote.RemotePath>`; if it is a path, a command
        representing this path will be returned; otherwise, the program name will be looked up in
        the system's ``PATH`` (using ``which``). Usage::

            r_ls = rem["ls"]
        """
        ...

    @property

    def python(self):  # -> RemoteCommand:
        """A command that represents the default remote python interpreter"""
        ...

    def session(self, isatty=..., *, new_session=...):
        """Creates a new :class:`ShellSession <plumbum.session.ShellSession>` object; this invokes the user's
        shell on the remote machine and executes commands on it over stdin/stdout/stderr
        """
        ...

    def download(self, src, dst):
        """Downloads a remote file/directory (``src``) to a local destination (``dst``).
        ``src`` must be a string or a :class:`RemotePath <plumbum.path.remote.RemotePath>`
        pointing to this remote machine, and ``dst`` must be a string or a
        :class:`LocalPath <plumbum.machines.local.LocalPath>`"""
        ...

    def upload(self, src, dst):
        """Uploads a local file/directory (``src``) to a remote destination (``dst``).
        ``src`` must be a string or a :class:`LocalPath <plumbum.machines.local.LocalPath>`,
        and ``dst`` must be a string or a :class:`RemotePath <plumbum.path.remote.RemotePath>`
        pointing to this remote machine"""
        ...

    def popen(self, args, **kwargs):
        """Spawns the given command on the remote machine, returning a ``Popen``-like object;
        do not use this method directly, unless you need "low-level" control on the remote
        process"""
        ...

    def list_processes(self):  # -> Generator[ProcInfo, Any, None]:
        """
        Returns information about all running processes (on POSIX systems: using ``ps``)

        .. versionadded:: 1.3
        """
        ...

    def pgrep(self, pattern):  # -> Generator[ProcInfo, Any, None]:
        """
        Process grep: return information about all processes whose command-line args match the given regex pattern
        """
        ...

    @contextlib.contextmanager

    def tempdir(self):  # -> Generator[RemotePath, Any, None]:
        """A context manager that creates a remote temporary directory, which is removed when
        the context exits"""
        ...

    def expand(self, expr):
        ...

    def expanduser(self, expr):
        ...
