"""
This type stub file was generated by pyright.
"""


from plumbum.commands.processes import ProcessExecutionError
from plumbum.machines.base import PopenAddons


class ShellSessionError(Exception):
    """Raises when something goes wrong when calling
    :func:`ShellSession.popen <plumbum.session.ShellSession.popen>`"""

    ...


class SSHCommsError(ProcessExecutionError, EOFError):
    """Raises when the communication channel can't be created on the
    remote host or it times out."""

    ...


class SSHCommsChannel2Error(SSHCommsError):
    """Raises when channel 2 (stderr) is not available"""

    ...


class IncorrectLogin(SSHCommsError):
    """Raises when incorrect login credentials are provided"""

    ...


class HostPublicKeyUnknown(SSHCommsError):
    """Raises when the host public key isn't known"""

    ...

shell_logger = ...


class MarkedPipe:
    """A pipe-like object from which you can read lines; the pipe will return report EOF (the
    empty string) when a special marker is detected"""

    __slots__ = ...

    def __init__(self, pipe, marker) -> None:
        ...

    def close(self):  # -> None:
        """'Closes' the marked pipe; following calls to ``readline`` will return "" """
        ...

    def readline(self):  # -> Literal[b""]:
        """Reads the next line from the pipe; returns "" when the special marker is reached.
        Raises ``EOFError`` if the underlying pipe has closed"""
        ...


class SessionPopen(PopenAddons):
    """A shell-session-based ``Popen``-like object (has the following attributes: ``stdin``,
    ``stdout``, ``stderr``, ``returncode``)"""

    def __init__(self, proc, argv, isatty, stdin, stdout, stderr, encoding, *, host) -> None:
        ...

    def poll(self):  # -> int | str | None:
        """Returns the process' exit code or ``None`` if it's still running"""
        ...

    def wait(self):  # -> int | str | None:
        """Waits for the process to terminate and returns its exit code"""
        ...

    def communicate(self, input=...):  # -> tuple[bytes, bytes]:
        """Consumes the process' stdout and stderr until the it terminates.

        :param input: An optional bytes/buffer object to send to the process over stdin
        :returns: A tuple of (stdout, stderr)
        """
        ...


class ShellSession:
    """An abstraction layer over *shell sessions*. A shell session is the execution of an
    interactive shell (``/bin/sh`` or something compatible), over which you may run commands
    (sent over stdin). The output of is then read from stdout and stderr. Shell sessions are
    less "robust" than executing a process on its own, and they are susseptible to all sorts
    of malformatted-strings attacks, and there is little benefit from using them locally.
    However, they can greatly speed up remote connections, and are required for the implementation
    of :class:`SshMachine <plumbum.machines.remote.SshMachine>`, as they allow us to send multiple
    commands over a single SSH connection (setting up separate SSH connections incurs a high
    overhead). Try to avoid using shell sessions, unless you know what you're doing.

    Instances of this class may be used as *context-managers*.

    :param proc: The underlying shell process (with open stdin, stdout and stderr)
    :param encoding: The encoding to use for the shell session. If ``"auto"``, the underlying
                     process' encoding is used.
    :param isatty: If true, assume the shell has a TTY and that stdout and stderr are unified
    :param connect_timeout: The timeout to connect to the shell, after which, if no prompt
                            is seen, the shell process is killed
    """

    def __init__(self, proc, encoding=..., isatty=..., connect_timeout=..., *, host=...) -> None:
        ...

    def __enter__(self):  # -> Self:
        ...

    def __exit__(self, t, v, tb):  # -> None:
        ...

    def __del__(self):  # -> None:
        ...

    def alive(self):  # -> bool | None:
        """Returns ``True`` if the underlying shell process is alive, ``False`` otherwise"""
        ...

    def close(self):  # -> None:
        """Closes (terminates) the shell session"""
        ...

    def popen(self, cmd):  # -> SessionPopen:
        """Runs the given command in the shell, adding some decoration around it. Only a single
        command can be executed at any given time.

        :param cmd: The command (string or :class:`Command <plumbum.commands.BaseCommand>` object)
                    to run
        :returns: A :class:`SessionPopen <plumbum.session.SessionPopen>` instance
        """
        ...

    def run(self, cmd, retcode=...):  # -> tuple[Any, str | Any | Literal[b""], str | Any | Literal[b""]]:
        """Runs the given command

        :param cmd: The command (string or :class:`Command <plumbum.commands.BaseCommand>` object)
                    to run
        :param retcode: The expected return code (0 by default). Set to ``None`` in order to
                        ignore erroneous return codes
        :returns: A tuple of (return code, stdout, stderr)
        """
        ...
