"""
This type stub file was generated by pyright.
"""


from plumbum.machines.remote import BaseRemoteMachine


class SshTunnel:
    """An object representing an SSH tunnel (created by
    :func:`SshMachine.tunnel <plumbum.machines.remote.SshMachine.tunnel>`)"""

    __slots__ = ...

    def __init__(self, session, lport, dport, reverse) -> None:
        ...

    def __repr__(self):  # -> str:
        ...

    def __enter__(self):  # -> Self:
        ...

    def __exit__(self, t, v, tb):  # -> None:
        ...

    def close(self):  # -> None:
        """Closes(terminates) the tunnel"""
        ...

    @property

    def lport(self):  # -> Any:
        """Tunneled port or socket on the local machine."""
        ...

    @property

    def dport(self):  # -> Any | str:
        """Tunneled port or socket on the remote machine."""
        ...

    @property

    def reverse(self):  # -> Any:
        """Represents if the tunnel is a reverse tunnel."""
        ...


class SshMachine(BaseRemoteMachine):
    """
    An implementation of :class:`remote machine <plumbum.machines.remote.BaseRemoteMachine>`
    over SSH. Invoking a remote command translates to invoking it over SSH ::

        with SshMachine("yourhostname") as rem:
            r_ls = rem["ls"]
            # r_ls is the remote `ls`
            # executing r_ls() translates to `ssh yourhostname ls`

    :param host: the host name to connect to (SSH server)

    :param user: the user to connect as (if ``None``, the default will be used)

    :param port: the server's port (if ``None``, the default will be used)

    :param keyfile: the path to the identity file (if ``None``, the default will be used)

    :param ssh_command: the ``ssh`` command to use; this has to be a ``Command`` object;
                        if ``None``, the default ssh client will be used.

    :param scp_command: the ``scp`` command to use; this has to be a ``Command`` object;
                        if ``None``, the default scp program will be used.

    :param ssh_opts: any additional options for ``ssh`` (a list of strings)

    :param scp_opts: any additional options for ``scp`` (a list of strings)

    :param password: the password to use; requires ``sshpass`` be installed. Cannot be used
                     in conjunction with ``ssh_command`` or ``scp_command`` (will be ignored).
                     NOTE: THIS IS A SECURITY RISK!

    :param encoding: the remote machine's encoding (defaults to UTF8)

    :param connect_timeout: specify a connection timeout (the time until shell prompt is seen).
                            The default is 10 seconds. Set to ``None`` to disable

    :param new_session: whether or not to start the background session as a new
                        session leader (setsid). This will prevent it from being killed on
                        Ctrl+C (SIGINT)
    """

    def __init__(
        self, host, user=..., port=..., keyfile=..., ssh_command=..., scp_command=..., ssh_opts=..., scp_opts=..., password=..., encoding=..., connect_timeout=..., new_session=...
    ) -> None: ...

    def __str__(self) -> str:
        ...

    def popen(self, args, ssh_opts=..., env=..., cwd=..., **kwargs):  # -> PlumbumLocalPopen:
        ...

    def nohup(self, command):  # -> None:
        """
        Runs the given command using ``nohup`` and redirects std handles,
        allowing the command to run "detached" from its controlling TTY or parent.
        Does not return anything. Depreciated (use command.nohup or daemonic_popen).
        """
        ...

    def daemonic_popen(self, command, cwd=..., stdout=..., stderr=..., append=...):  # -> None:
        """
        Runs the given command using ``nohup`` and redirects std handles,
        allowing the command to run "detached" from its controlling TTY or parent.
        Does not return anything.

        .. versionadded:: 1.6.0

        """
        ...

    def session(self, isatty=..., new_session=...):  # -> ShellSession:
        ...

    def tunnel(self, lport, dport, lhost=..., dhost=..., connect_timeout=..., reverse=...):  # -> SshTunnel:
        r"""Creates an SSH tunnel from the TCP port (``lport``) of the local machine
        (``lhost``, defaults to ``"localhost"``, but it can be any IP you can ``bind()``)
        to the remote TCP port (``dport``) of the destination machine (``dhost``, defaults
        to ``"localhost"``, which means *this remote machine*). This function also
        supports Unix sockets, in which case the local socket should be passed in as
        ``lport`` and the local bind address should be ``None``. The same can be done
        for a remote socket, by following the same pattern with ``dport`` and ``dhost``.
        The returned :class:`SshTunnel <plumbum.machines.remote.SshTunnel>` object can
        be used as a *context-manager*.

        The more conventional use case is the following::

            +---------+          +---------+
            | Your    |          | Remote  |
            | Machine |          | Machine |
            +----o----+          +---- ----+
                 |                    ^
                 |                    |
               lport                dport
                 |                    |
                 \______SSH TUNNEL____/
                        (secure)

        Here, you wish to communicate safely between port ``lport`` of your machine and
        port ``dport`` of the remote machine. Communication is tunneled over SSH, so the
        connection is authenticated and encrypted.

        The more general case is shown below (where ``dport != "localhost"``)::

            +---------+          +-------------+      +-------------+
            | Your    |          | Remote      |      | Destination |
            | Machine |          | Machine     |      | Machine     |
            +----o----+          +---- ----o---+      +---- --------+
                 |                    ^    |               ^
                 |                    |    |               |
            lhost:lport               |    |          dhost:dport
                 |                    |    |               |
                 \_____SSH TUNNEL_____/    \_____SOCKET____/
                        (secure)              (not secure)

        Usage::

            rem = SshMachine("megazord")

            with rem.tunnel(1234, "/var/lib/mysql/mysql.sock", dhost=None):
                sock = socket.socket()
                sock.connect(("localhost", 1234))
                # sock is now tunneled to the MySQL socket on megazord
        """
        ...

    def download(self, src, dst):  # -> None:
        ...

    def upload(self, src, dst):  # -> None:
        ...


class PuttyMachine(SshMachine):
    """
    PuTTY-flavored SSH connection. The programs ``plink`` and ``pscp`` are expected to
    be in the path (or you may provide your own ``ssh_command`` and ``scp_command``)

    Arguments are the same as for :class:`plumbum.machines.remote.SshMachine`
    """

    def __init__(
        self, host, user=..., port=..., keyfile=..., ssh_command=..., scp_command=..., ssh_opts=..., scp_opts=..., encoding=..., connect_timeout=..., new_session=...
    ) -> None: ...

    def __str__(self) -> str:
        ...

    def session(self, isatty=..., new_session=...):  # -> ShellSession:
        ...
