"""
This type stub file was generated by pyright.
"""


__b58chars = ...
__b58base = ...


def b58encode(v):  # -> str:
    """encode v, which is bytes, to base58 string."""
    ...


def b58decode(v, length):  # -> bytes | None:
    """decode v (string) into bytes."""
    ...


def get_bcaddress_version(strAddress):  # -> int | None:
    """Returns None if strAddress is invalid. Otherwise returns integer version of address."""
    ...


if __name__ == "__main__":
    _ohai = ...
    _tmp = ...
