"""
This type stub file was generated by pyright.
"""


import plumbum


def __getattr__(name: str) -> plumbum.machines.LocalCommand:
    """The module-hack that allows us to use ``from plumbum.cmd import some_program``"""
    ...
