"""
This type stub file was generated by pyright.
"""


"""
This module imitates a real module, providing standard syntax
like from `plumbum.colors` and from `plumbum.colors.bg` to work alongside
all the standard syntax for colors.
"""
_reset = ...


if __name__ == "__main__":
    ...
else:
    ...
