"""
This type stub file was generated by pyright.
"""


from contextlib import contextmanager

IS_WIN32 = ...


class ProcInfo:

    def __init__(self, pid, uid, stat, args) -> None:
        ...

    def __repr__(self):  # -> str:
        ...

@contextmanager


def captured_stdout(stdin=...):  # -> Generator[StringIO, Any, None]:
    """
    Captures stdout (similar to the redirect_stdout in Python 3.4+, but with slightly different arguments)
    """
    ...


class StaticProperty:
    """This acts like a static property, allowing access via class or object.
    This is a non-data descriptor."""

    def __init__(self, function) -> None:
        ...

    def __get__(self, obj, klass=...):
        ...


def getdoc(obj):  # -> str | None:
    """
    This gets a docstring if available, and cleans it, but does not look up docs in
    inheritance tree (Pre Python 3.5 behavior of ``inspect.getdoc``).
    """
    ...


def read_fd_decode_safely(fd, size=...):  # -> tuple[bytes, str]:
    """
    This reads a utf-8 file descriptor and returns a chunk, growing up to
    three bytes if needed to decode the character at the end.

    Returns the data and the decoded text.
    """
    ...
