"""
This type stub file was generated by pyright.
"""


from collections.abc import MutableMapping

NO_DEFAULT = ...


class EnvironmentVariableError(KeyError):
    ...


class TypedEnv(MutableMapping):
    """
    This object can be used in 'exploratory' mode:

        nv = TypedEnv()
        print(nv.HOME)

    It can also be used as a parser and validator of environment variables:

    class MyEnv(TypedEnv):
        username = TypedEnv.Str("USER", default='anonymous')
        path = TypedEnv.CSV("PATH", separator=":")
        tmp = TypedEnv.Str("TMP TEMP".split())  # support 'fallback' var-names

    nv = MyEnv()

    print(nv.username)

    for p in nv.path:
        print(p)

    try:
        print(p.tmp)
    except EnvironmentVariableError:
        print("TMP/TEMP is not defined")
    else:
        assert False
    """

    __slots__ = ...

    class _BaseVar:

        def __init__(self, name, default=...) -> None:
            ...

        def convert(self, value):
            ...

        def __get__(self, instance, owner):  # -> Self | object:
            ...

        def __set__(self, instance, value):  # -> None:
            ...

    class Str(_BaseVar):
        ...

    class Bool(_BaseVar):
        """
        Converts 'yes|true|1|no|false|0' to the appropriate boolean value.
        Case-insensitive. Throws a ``ValueError`` for any other value.
        """

        def convert(self, value):  # -> bool:
            ...

        def __set__(self, instance, value):  # -> None:
            ...

    class Int(_BaseVar):
        convert = ...

    class Float(_BaseVar):
        convert = ...

    class CSV(_BaseVar):
        """
        Comma-separated-strings get split using the ``separator`` (',' by default) into
        a list of objects of type ``type`` (``str`` by default).
        """

        def __init__(self, name, default=..., type=..., separator=...) -> None:
            ...

        def __set__(self, instance, value):  # -> None:
            ...

        def convert(self, value):  # -> list[str]:
            ...

    def __init__(self, env=...) -> None:
        ...

    def __iter__(self):  # -> Iterator[str]:
        ...

    def __len__(self):  # -> int:
        ...

    def __delitem__(self, name):  # -> None:
        ...

    def __setitem__(self, name, value):  # -> None:
        ...

    def __contains__(self, key):  # -> bool:
        ...

    def __getattr__(self, name):  # -> str | object:
        ...

    def __getitem__(self, key):  # -> Any:
        ...

    def get(self, key, default=...):  # -> Any | None:
        ...

    def __dir__(self):  # -> list[str]:
        ...
