"""
This type stub file was generated by pyright.
"""


import functools
import inspect
from rpyc.core import DEFAULT_CONFIG

"""
Utilities (not part of the core protocol)
"""


def service(cls):
    """find and rename exposed decorated attributes"""
    ...


def exposed(arg):  # -> partial[Any]:
    """decorator that adds the exposed prefix information to functions which `service` uses to rebind attrs"""
    ...
