"""
This type stub file was generated by pyright.
"""


"""
RPyC Registry Server maintains service information on RPyC services for *Service Registry and Discovery patterns*. Service Registry and Discovery patterns solve the connectivity problem for communication between services and external consumers. RPyC services will register with the server when :code:`auto_register` is :code:`True`.

Service registries such as `Avahi <https://en.wikipedia.org/wiki/Avahi_(software)>`_ and
`Bonjour <https://en.wikipedia.org/wiki/Bonjour_(software)>`_ are alternatives to the RPyC Registry Server. These alternatives do no support Windows and have more restrictive licensing.

Refer to :file:`rpyc/scripts/rpyc_registry.py` for more info.
"""
DEFAULT_PRUNING_TIMEOUT = ...
MAX_DGRAM_SIZE = ...
REGISTRY_PORT = ...


class RegistryServer:
    """Base registry server"""

    def __init__(self, listenersock, pruning_timeout=..., logger=..., allow_listing=...) -> None:
        ...

    def on_service_added(self, name, addrinfo):  # -> None:
        """called when a new service joins the registry (but not on keepalives).
        override this to add custom logic"""
        ...

    def on_service_removed(self, name, addrinfo):  # -> None:
        """called when a service unregisters or is pruned.
        override this to add custom logic"""
        ...

    def cmd_query(self, host, name):  # -> tuple[()] | tuple[Any, ...]:
        """implementation of the ``query`` command"""
        ...

    def cmd_list(self, host, filter_host):  # -> tuple[Any, ...] | None:
        """implementation for the ``list`` command"""
        ...

    def cmd_register(self, host, names, port):  # -> Literal['OK']:
        """implementation of the ``register`` command"""
        ...

    def cmd_unregister(self, host, port):  # -> Literal['OK']:
        """implementation of the ``unregister`` command"""
        ...

    def start(self):  # -> None:
        """Starts the registry server (blocks)"""
        ...

    def close(self):  # -> None:
        """Closes (terminates) the registry server"""
        ...


class UDPRegistryServer(RegistryServer):
    """UDP-based registry server. The server listens to UDP broadcasts and
    answers them. Useful in local networks, were broadcasts are allowed"""

    TIMEOUT = ...

    def __init__(self, host=..., port=..., pruning_timeout=..., logger=..., allow_listing=...) -> None:
        ...


class TCPRegistryServer(RegistryServer):
    """TCP-based registry server. The server listens to a certain TCP port and
    answers requests. Useful when you need to cross routers in the network, since
    they block UDP broadcasts"""

    TIMEOUT = ...

    def __init__(self, host=..., port=..., pruning_timeout=..., logger=..., reuse_addr=..., allow_listing=...) -> None:
        ...


class RegistryClient:
    """Base registry client. Also known as **registrar**"""

    REREGISTER_INTERVAL = ...

    def __init__(self, ip, port, timeout, logger=...) -> None:
        ...

    def discover(self, name):
        """Sends a query for the specified service name.

        :param name: the service name (or one of its aliases)

        :returns: a list of ``(host, port)`` tuples
        """
        ...

    def list(self, filter_host=...):
        """
        Send a query for the full lists of exposed servers
        :returns: a list of `` service_name ``
        """
        ...

    def register(self, aliases, port):
        """Registers the given service aliases with the given TCP port. This
        API is intended to be called only by an RPyC server.

        :param aliases: the :class:`service's <rpyc.core.service.Service>` aliases
        :param port: the listening TCP port of the server
        """
        ...

    def unregister(self, port):
        """Unregisters the given RPyC server. This API is intended to be called
        only by an RPyC server.

        :param port: the listening TCP port of the RPyC server to unregister
        """
        ...


class UDPRegistryClient(RegistryClient):
    """UDP-based registry clients. By default, it sends UDP broadcasts (requires
    special user privileges on certain OS's) and collects the replies. You can
    also specify the IP address to send to.

    Example::

        registrar = UDPRegistryClient()
        list_of_services = registrar.list()
        list_of_servers = registrar.discover("foo")

    .. note::
       Consider using :func:`rpyc.utils.factory.discover` instead
    """

    def __init__(self, ip=..., port=..., timeout=..., bcast=..., logger=..., ipv6=...) -> None:
        ...

    def discover(self, name):  # -> int | tuple[()]:
        ...

    def list(self, filter_host=...):  # -> int | tuple[()]:
        ...

    def register(self, aliases, port, interface=...):  # -> bool:
        ...

    def unregister(self, port):  # -> None:
        ...


class TCPRegistryClient(RegistryClient):
    """TCP-based registry client. You must specify the host (registry server)
    to connect to.

    Example::

        registrar = TCPRegistryClient("localhost")
        list_of_services = registrar.list()
        list_of_servers = registrar.discover("foo")

    .. note::
       Consider using :func:`rpyc.utils.factory.discover` instead
    """

    def __init__(self, ip, port=..., timeout=..., logger=...) -> None:
        ...

    def discover(self, name):  # -> int | tuple[()]:
        ...

    def list(self, filter_host=...):  # -> int | tuple[()]:
        ...

    def register(self, aliases, port, interface=...):  # -> bool:
        ...

    def unregister(self, port):  # -> None:
        ...
