"""
This type stub file was generated by pyright.
"""


"""
rpyc plug-in server (threaded or forking)
"""
signal = ...
gevent = ...


class Server:
    """Base server implementation

    :param service: the :class:`~rpyc.core.service.Service` to expose
    :param hostname: the host to bind to. By default, the 'wildcard address' is used to listen on all interfaces.
                     if not properly secured, the server can receive traffic from unintended or even malicious sources.
    :param ipv6: whether to create an IPv6 or IPv4 socket. The default is IPv4
    :param port: the TCP port to bind to
    :param backlog: the socket's backlog (passed to ``listen()``)
    :param reuse_addr: whether or not to create the socket with the ``SO_REUSEADDR`` option set.
    :param authenticator: the :ref:`api-authenticators` to use. If ``None``, no authentication
                          is performed.
    :param registrar: the :class:`~rpyc.utils.registry.RegistryClient` to use.
                          If ``None``, a default :class:`~rpyc.utils.registry.UDPRegistryClient`
                          will be used
    :param auto_register: whether or not to register using the *registrar*. By default, the
                          server will attempt to register only if a registrar was explicitly given.
    :param protocol_config: the :data:`configuration dictionary <rpyc.core.protocol.DEFAULT_CONFIG>`
                            that is passed to the RPyC connection
    :param logger: the ``logger`` to use (of the built-in ``logging`` module). If ``None``, a
                   default logger will be created.
    :param listener_timeout: the timeout of the listener socket; set to ``None`` to disable (e.g.
                             on embedded platforms with limited battery)
    """

    def __init__(
        self,
        service,
        hostname=...,
        ipv6=...,
        port=...,
        backlog=...,
        reuse_addr=...,
        authenticator=...,
        registrar=...,
        auto_register=...,
        protocol_config=...,
        logger=...,
        listener_timeout=...,
        socket_path=...,
    ) -> None: ...

    def close(self):  # -> None:
        """Closes (terminates) the server and all of its clients. If applicable,
        also unregisters from the registry server"""
        ...

    def fileno(self):  # -> int:
        """returns the listener socket's file descriptor"""
        ...

    def accept(self):  # -> None:
        """accepts an incoming socket connection (blocking)"""
        ...

    def start(self):  # -> None:
        """Starts the server (blocking). Use :meth:`close` to stop"""
        ...


class OneShotServer(Server):
    """
    A server that handles a single connection (blockingly), and terminates after that

    Parameters: see :class:`Server`
    """

    ...


class ThreadedServer(Server):
    """
    A server that spawns a thread for each connection. Works on any platform
    that supports threads.

    Parameters: see :class:`Server`
    """

    ...


class ThreadPoolServer(Server):
    """This server is threaded like the ThreadedServer but reuses threads so that
    recreation is not necessary for each request. The pool of threads has a fixed
    size that can be set with the 'nbThreads' argument. The default size is 20.
    The server dispatches request to threads by batch, that is a given thread may process
    up to request_batch_size requests from the same connection in one go, before it goes to
    the next connection with pending requests. By default, self.request_batch_size
    is set to 10 and it can be overwritten in the constructor arguments.

    Contributed by *@sponce*

    Parameters: see :class:`Server`
    """

    def __init__(self, *args, **kwargs) -> None:
        """Initializes a ThreadPoolServer. In particular, instantiate the thread pool."""
        ...

    def close(self):  # -> None:
        """closes a ThreadPoolServer. In particular, joins the thread pool."""
        ...


class ForkingServer(Server):
    """
    A server that forks a child process for each connection. Available on
    POSIX compatible systems only.

    Parameters: see :class:`Server`
    """

    def __init__(self, *args, **kwargs) -> None:
        ...

    def close(self):  # -> None:
        ...


class GeventServer(Server):
    """gevent based Server. Requires using ``gevent.monkey.patch_all()``."""

    ...
