"""
This type stub file was generated by pyright.
"""


CODEOBJ_MAGIC = ...
CODE_HAVEARG_SIZE = ...


def decode_codeobj(codeobj):  # -> Generator[tuple[Any, Any], Any, None]:
    ...


def export_function(
    func,
):  # -> tuple[Any, Any, Any, tuple[Any, ...] | Any, tuple[Any, Any, Any, Any, Any, Any, Any, tuple[Any, ...], Any, Any, Any, Any, Any, Any, Any, Any, Any, Any] | tuple[Any, Any, Any, Any, Any, Any, Any, tuple[Any, ...], Any, Any, Any, Any, Any, Any, Any, Any] | tuple[Any, Any, Any, Any, Any, Any, tuple[Any, ...], Any, Any, Any, Any, Any, Any, Any, Any]]:
    ...


def import_function(functup, globals=..., def_=...):  # -> FunctionType:
    ...
