"""
This type stub file was generated by pyright.
"""


import pkg_resources
from .utils import LOG, TimeoutException
from .threadstop import ThreadingTimeout, async_raise, threading_timeoutable
from .signalstop import SignalTimeout, signal_timeoutable

"""
======
stopit
======

Public resources from ``stopit``
"""
__version__ = ...
__all__ = ("ThreadingTimeout", "async_raise", "threading_timeoutable", "SignalTimeout", "signal_timeoutable")
