"""
This type stub file was generated by pyright.
"""


from .utils import BaseTimeout, base_timeoutable

"""
=================
stopit.signalstop
=================

Control the timeout of blocks or callables with a context manager or a
decorator. Based on the use of signal.SIGALRM
"""


class SignalTimeout(BaseTimeout):
    """Context manager for limiting in the time the execution of a block
    using signal.SIGALRM Unix signal.

    See :class:`stopit.utils.BaseTimeout` for more information
    """

    def __init__(self, seconds, swallow_exc=...) -> None:
        ...

    def handle_timeout(self, signum, frame):
        ...

    def setup_interrupt(self):  # -> None:
        ...

    def suppress_interrupt(self):  # -> None:
        ...


class signal_timeoutable(base_timeoutable):
    """A function or method decorator that raises a ``TimeoutException`` to
    decorated functions that should not last a certain amount of time.
    this one uses ``SignalTimeout`` context manager.

    See :class:`.utils.base_timoutable`` class for further comments.
    """

    to_ctx_mgr = SignalTimeout
