"""
This type stub file was generated by pyright.
"""


from .utils import BaseTimeout, base_timeoutable

"""
=================
stopit.threadstop
=================

Raise asynchronous exceptions in other thread, control the timeout of blocks
or callables with a context manager or a decorator.
"""


def async_raise(target_tid, exception):  # -> None:
    """Raises an asynchronous exception in another thread.
    Read http://docs.python.org/c-api/init.html#PyThreadState_SetAsyncExc
    for further enlightenments.

    :param target_tid: target thread identifier
    :param exception: Exception class to be raised in that thread
    """
    ...


class ThreadingTimeout(BaseTimeout):
    """Context manager for limiting in the time the execution of a block
    using asynchronous threads launching exception.

    See :class:`stopit.utils.BaseTimeout` for more information
    """

    def __init__(self, seconds, swallow_exc=...) -> None:
        ...

    def stop(self):  # -> None:
        """Called by timer thread at timeout. Raises a Timeout exception in the
        caller thread
        """
        ...

    def setup_interrupt(self):  # -> None:
        """Setting up the resource that interrupts the block"""
        ...

    def suppress_interrupt(self):  # -> None:
        """Removing the resource that interrupts the block"""
        ...


class threading_timeoutable(base_timeoutable):
    """A function or method decorator that raises a ``TimeoutException`` to
    decorated functions that should not last a certain amount of time.
    this one uses ``ThreadingTimeout`` context manager.

    See :class:`.utils.base_timoutable`` class for further comments.
    """

    to_ctx_mgr = ThreadingTimeout
