"""
This type stub file was generated by pyright.
"""


import sys

"""
============
stopit.utils
============

Misc utilities and common resources
"""
LOG = ...


if sys.version_info < (2, 7):
    ...
else:
    ...


class TimeoutException(Exception):
    """Raised when the block under context management takes longer to complete
    than the allowed maximum timeout value.
    """

    ...


class BaseTimeout:
    """Context manager for limiting in the time the execution of a block

    :param seconds: ``float`` or ``int`` duration enabled to run the context
      manager block
    :param swallow_exc: ``False`` if you want to manage the
      ``TimeoutException`` (or any other) in an outer ``try ... except``
      structure. ``True`` (default) if you just want to check the execution of
      the block with the ``state`` attribute of the context manager.
    """

    def __init__(self, seconds, swallow_exc=...) -> None:
        ...

    def __bool__(self):  # -> bool:
        ...
    __nonzero__ = ...

    def __repr__(self):  # -> str:
        """Debug helper"""
        ...

    def __enter__(self):  # -> Self:
        ...

    def __exit__(self, exc_type, exc_val, exc_tb):  # -> bool:
        ...

    def cancel(self):  # -> None:
        """In case in the block you realize you don't need anymore
        limitation"""
        ...

    def suppress_interrupt(self):
        """Removes/neutralizes the feature that interrupts the executed block"""
        ...

    def setup_interrupt(self):
        """Installs/initializes the feature that interrupts the executed block"""
        ...


class base_timeoutable:
    """A base for function or method decorator that raises a ``TimeoutException`` to
    decorated functions that should not last a certain amount of time.

    Any decorated callable may receive a ``timeout`` optional parameter that
    specifies the number of seconds allocated to the callable execution.

    The decorated functions that exceed that timeout return ``None`` or the
    value provided by the decorator.

    :param default: The default value in case we timed out during the decorated
      function execution. Default is None.

    :param timeout_param: As adding dynamically a ``timeout`` named parameter
      to the decorated callable may conflict with the callable signature, you
      may choose another name to provide that parameter. Your decoration line
      could look like ``@timeoutable(timeout_param='my_timeout')``

    .. note::

       This is a base class that must be subclassed. subclasses must override
       thz ``to_ctx_mgr`` with a timeout  context manager class which in turn
       must subclasses of above ``BaseTimeout`` class.
    """

    to_ctx_mgr = ...

    def __init__(self, default=..., timeout_param=...) -> None:
        ...

    def __call__(self, func):  # -> _Wrapped[Callable[..., Any], Any, Callable[..., Any], Any]:
        ...
