"""
This type stub file was generated by pyright.
"""


import warnings
import PIL
from typing import Any, Iterable, Iterator, Tuple

"""Python image steganography

Stepic hides arbitrary data inside PIL images.

Stepic uses the Python Image Library
(apt: python-imaging, web: <http://www.pythonware.com/products/pil/>).
"""
__author__ = ...
__version__ = ...
__all__ = ("encode_imdata", "encode_inplace", "encode", "decode_imdata", "decode", "Steganographer")


def encode_imdata(imdata: Iterable[Tuple[int, int, int]], data: bytes) -> Iterator[Tuple[int, int, int]]:
    """given a sequence of pixels, returns an iterator of pixels with
    encoded data"""
    ...


def encode_inplace(image: Any, data: bytes) -> None:
    """hides data in an image"""
    ...


def encode(image: Any, data: bytes) -> Any:
    """generates an image with hidden data, starting with an existing
    image and arbitrary data"""
    ...


def decode_imdata(imdata: Iterable[Tuple[int, int, int]]) -> Iterator[bytes]:
    """Given a sequence of pixels, returns an iterator of characters
    encoded in the image"""
    ...


def decode(image: Any) -> bytes:
    """extracts data from an image"""
    ...


class Steganographer:
    "deprecated"

    def __init__(self, image: Any) -> None:
        ...

    def encode(self, data: bytes) -> Any:
        ...

    def decode(self) -> bytes:
        ...
