"""
This type stub file was generated by pyright.
"""


import builtins
import io
import os
import typing
from abc import ABC, abstractmethod

FLAGS = ...


class FSUser(int):
    """A special object that represents a file-system user. It derives from ``int``, so it behaves
    just like a number (``uid``/``gid``), but also have a ``.name`` attribute that holds the
    string-name of the user, if given (otherwise ``None``)
    """

    def __new__(cls, val, name=...):  # -> Self:
        ...

_PathImpl = typing.TypeVar("_PathImpl", bound="Path")


class Path(str, ABC):
    """An abstraction over file system paths. This class is abstract, and the two implementations
    are :class:`LocalPath <plumbum.machines.local.LocalPath>` and
    :class:`RemotePath <plumbum.path.remote.RemotePath>`.
    """

    CASE_SENSITIVE = ...

    def __repr__(self):  # -> str:
        ...

    def __truediv__(self: _PathImpl, other: typing.Any) -> _PathImpl:
        """Joins two paths"""
        ...

    def __getitem__(self, key):  # -> Self | str:
        ...

    def __floordiv__(self, expr):  # -> list[Self]:
        """Returns a (possibly empty) list of paths that matched the glob-pattern under this path"""
        ...

    def __iter__(self):  # -> Iterator[Self]:
        """Iterate over the files in this directory"""
        ...

    def __eq__(self, other: object) -> bool:
        ...

    def __ne__(self, other) -> bool:
        ...

    def __gt__(self, other) -> bool:
        ...

    def __ge__(self, other) -> bool:
        ...

    def __lt__(self, other) -> bool:
        ...

    def __le__(self, other) -> bool:
        ...

    def __hash__(self) -> int:
        ...

    def __bool__(self):  # -> bool:
        ...

    def __fspath__(self):  # -> str:
        """Added for Python 3.6 support"""
        ...

    def __contains__(self, item):
        """Paths should support checking to see if an file or folder is in them."""
        ...

    def up(self, count=...):  # -> Self:
        """Go up in ``count`` directories (the default is 1)"""
        ...

    def walk(self, filter=..., dir_filter=...):  # -> Generator[Self | Any, Any, None]:
        """traverse all (recursive) sub-elements under this directory, that match the given filter.
        By default, the filter accepts everything; you can provide a custom filter function that
        takes a path as an argument and returns a boolean

        :param filter: the filter (predicate function) for matching results. Only paths matching
                       this predicate are returned. Defaults to everything.
        :param dir_filter: the filter (predicate function) for matching directories. Only directories
                           matching this predicate are recursed into. Defaults to everything.
        """
        ...

    @property
    @abstractmethod

    def name(self) -> str:
        """The basename component of this path"""
        ...

    @property

    def basename(self):  # -> str:
        """Included for compatibility with older Plumbum code"""
        ...

    @property
    @abstractmethod

    def stem(self) -> str:
        """The name without an extension, or the last component of the path"""
        ...

    @property
    @abstractmethod

    def dirname(self: _PathImpl) -> _PathImpl:
        """The dirname component of this path"""
        ...

    @property
    @abstractmethod

    def root(self) -> str:
        """The root of the file tree (`/` on Unix)"""
        ...

    @property
    @abstractmethod

    def drive(self) -> str:
        """The drive letter (on Windows)"""
        ...

    @property
    @abstractmethod

    def suffix(self) -> str:
        """The suffix of this file"""
        ...

    @property
    @abstractmethod

    def suffixes(self) -> list[str]:
        """This is a list of all suffixes"""
        ...

    @property
    @abstractmethod

    def uid(self) -> FSUser:
        """The user that owns this path. The returned value is a :class:`FSUser <plumbum.path.FSUser>`
        object which behaves like an ``int`` (as expected from ``uid``), but it also has a ``.name``
        attribute that holds the string-name of the user"""
        ...

    @property
    @abstractmethod

    def gid(self) -> FSUser:
        """The group that owns this path. The returned value is a :class:`FSUser <plumbum.path.FSUser>`
        object which behaves like an ``int`` (as expected from ``gid``), but it also has a ``.name``
        attribute that holds the string-name of the group"""
        ...

    @abstractmethod

    def as_uri(self, scheme: str | None = ...) -> str:
        """Returns a universal resource identifier. Use ``scheme`` to force a scheme."""
        ...

    @abstractmethod

    def join(self: _PathImpl, *parts: typing.Any) -> _PathImpl:
        """Joins this path with any number of paths"""
        ...

    @abstractmethod

    def list(self: _PathImpl) -> builtins.list[_PathImpl]:
        """Returns the files in this directory"""
        ...

    @abstractmethod

    def iterdir(self: _PathImpl) -> typing.Iterable[_PathImpl]:
        """Returns an iterator over the directory. Might be slightly faster on Python 3.5 than .list()"""
        ...

    @abstractmethod

    def is_dir(self) -> bool:
        """Returns ``True`` if this path is a directory, ``False`` otherwise"""
        ...

    def isdir(self):  # -> bool:
        """Included for compatibility with older Plumbum code"""
        ...

    @abstractmethod

    def is_file(self) -> bool:
        """Returns ``True`` if this path is a regular file, ``False`` otherwise"""
        ...

    def isfile(self) -> bool:
        """Included for compatibility with older Plumbum code"""
        ...

    def islink(self):  # -> bool:
        """Included for compatibility with older Plumbum code"""
        ...

    @abstractmethod

    def is_symlink(self) -> bool:
        """Returns ``True`` if this path is a symbolic link, ``False`` otherwise"""
        ...

    @abstractmethod

    def exists(self) -> bool:
        """Returns ``True`` if this path exists, ``False`` otherwise"""
        ...

    @abstractmethod

    def stat(self) -> os.stat_result:
        """Returns the os.stats for a file"""
        ...

    @abstractmethod

    def with_name(self: _PathImpl, name: typing.Any) -> _PathImpl:
        """Returns a path with the name replaced"""
        ...

    @abstractmethod

    def with_suffix(self: _PathImpl, suffix: str, depth: int | None = ...) -> _PathImpl:
        """Returns a path with the suffix replaced. Up to last ``depth`` suffixes will be
        replaced. None will replace all suffixes. If there are less than ``depth`` suffixes,
        this will replace all suffixes. ``.tar.gz`` is an example where ``depth=2`` or
        ``depth=None`` is useful"""
        ...

    def preferred_suffix(self, suffix):  # -> Self:
        """Adds a suffix if one does not currently exist (otherwise, no change). Useful
        for loading files with a default suffix"""
        ...

    @abstractmethod

    def glob(self: _PathImpl, pattern: str | typing.Iterable[str]) -> builtins.list[_PathImpl]:
        """Returns a (possibly empty) list of paths that matched the glob-pattern under this path"""
        ...

    @abstractmethod

    def delete(self):  # -> None:
        """Deletes this path (recursively, if a directory)"""
        ...

    @abstractmethod

    def move(self, dst):  # -> None:
        """Moves this path to a different location"""
        ...

    def rename(self, newname):  # -> None:
        """Renames this path to the ``new name`` (only the basename is changed)"""
        ...

    @abstractmethod

    def copy(self, dst, override=...):  # -> None:
        """Copies this path (recursively, if a directory) to the destination path "dst".
        Raises TypeError if dst exists and override is False.
        Will overwrite if override is True.
        Will silently fail to copy if override is None (the default)."""
        ...

    @abstractmethod

    def mkdir(self, mode=..., parents=..., exist_ok=...):  # -> None:
        """
        Creates a directory at this path.

        :param mode: **Currently only implemented for local paths!** Numeric mode to use for directory
                     creation, which may be ignored on some systems. The current implementation
                     reproduces the behavior of ``os.mkdir`` (i.e., the current umask is first masked
                     out), but this may change for remote paths. As with ``os.mkdir``, it is recommended
                     to call :func:`chmod` explicitly if you need to be sure.
        :param parents: If this is true (the default), the directory's parents will also be created if
                        necessary.
        :param exist_ok: If this is true (the default), no exception will be raised if the directory
                         already exists (otherwise ``OSError``).

        Note that the defaults for ``parents`` and ``exist_ok`` are the opposite of what they are in
        Python's own ``pathlib`` - this is to maintain backwards-compatibility with Plumbum's behaviour
        from before they were implemented.
        """
        ...

    @abstractmethod

    def open(self, mode: str = ..., *, encoding: str | None = ...) -> io.IOBase:
        """opens this path as a file"""
        ...

    @abstractmethod

    def read(self, encoding: str | None = ...) -> str:
        """returns the contents of this file as a ``str``. By default the data is read
        as text, but you can specify the encoding, e.g., ``'latin1'`` or ``'utf8'``"""
        ...

    @abstractmethod

    def write(self, data: str | bytes, encoding: str | None = ...) -> None:
        """writes the given data to this file. By default the data is written as-is
        (either text or binary), but you can specify the encoding, e.g., ``'latin1'``
        or ``'utf8'``"""
        ...

    @abstractmethod

    def touch(self):  # -> None:
        """Update the access time. Creates an empty file if none exists."""
        ...

    @abstractmethod

    def chown(self, owner=..., group=..., recursive=...):  # -> None:
        """Change ownership of this path.

        :param owner: The owner to set (either ``uid`` or ``username``), optional
        :param group: The group to set (either ``gid`` or ``groupname``), optional
        :param recursive: whether to change ownership of all contained files and subdirectories.
                          Only meaningful when ``self`` is a directory. If ``None``, the value
                          will default to ``True`` if ``self`` is a directory, ``False`` otherwise.
        """
        ...

    @abstractmethod

    def chmod(self, mode):  # -> None:
        """Change the mode of path to the numeric mode.

        :param mode: file mode as for os.chmod
        """
        ...

    @abstractmethod

    def access(self, mode: int | str = ...) -> bool:
        """Test file existence or permission bits

        :param mode: a bitwise-or of access bits, or a string-representation thereof:
                     ``'f'``, ``'x'``, ``'r'``, ``'w'`` for ``os.F_OK``, ``os.X_OK``,
                     ``os.R_OK``, ``os.W_OK``
        """
        ...

    @abstractmethod

    def link(self, dst):  # -> None:
        """Creates a hard link from ``self`` to ``dst``

        :param dst: the destination path
        """
        ...

    @abstractmethod

    def symlink(self, dst):  # -> None:
        """Creates a symbolic link from ``self`` to ``dst``

        :param dst: the destination path
        """
        ...

    @abstractmethod

    def unlink(self):  # -> None:
        """Deletes a symbolic link"""
        ...

    def split(self, *_args, **_kargs):  # -> list[Any]:
        """Splits the path on directory separators, yielding a list of directories, e.g,
        ``"/var/log/messages"`` will yield ``['var', 'log', 'messages']``.
        """
        ...

    @property

    def parts(self):  # -> tuple[str, *tuple[Any, ...]]:
        """Splits the directory into parts, including the base directory, returns a tuple"""
        ...

    def relative_to(self, source):  # -> RelativePath:
        """Computes the "relative path" require to get from ``source`` to ``self``. They satisfy the invariant
        ``source_path + (target_path - source_path) == target_path``. For example::

            /var/log/messages - /var/log/messages = []
            /var/log/messages - /var              = [log, messages]
            /var/log/messages - /                 = [var, log, messages]
            /var/log/messages - /var/tmp          = [.., log, messages]
            /var/log/messages - /opt              = [.., var, log, messages]
            /var/log/messages - /opt/lib          = [.., .., var, log, messages]
        """
        ...

    def __sub__(self, other):  # -> RelativePath:
        """Same as ``self.relative_to(other)``"""
        ...

    def resolve(self, strict=...):  # -> Self:
        """Added to allow pathlib like syntax. Does nothing since
        Plumbum paths are always absolute. Does not (currently) resolve
        symlinks."""
        ...

    @property

    def parents(self):  # -> tuple[Self, ...]:
        """Pathlib like sequence of ancestors"""
        ...

    @property

    def parent(self):  # -> Self:
        """Pathlib like parent of the path."""
        ...


class RelativePath:
    """
    Relative paths are the "delta" required to get from one path to another.
    Note that relative path do not point at anything, and thus are not paths.
    Therefore they are system agnostic (but closed under addition)
    Paths are always absolute and point at "something", whether existent or not.

    Relative paths are created by subtracting paths (``Path.relative_to``)
    """

    def __init__(self, parts) -> None:
        ...

    def __str__(self) -> str:
        ...

    def __iter__(self):
        ...

    def __len__(self):  # -> int:
        ...

    def __getitem__(self, index):
        ...

    def __repr__(self):  # -> str:
        ...

    def __eq__(self, other) -> bool:
        ...

    def __ne__(self, other) -> bool:
        ...

    def __gt__(self, other) -> bool:
        ...

    def __ge__(self, other) -> bool:
        ...

    def __lt__(self, other) -> bool:
        ...

    def __le__(self, other) -> bool:
        ...

    def __hash__(self) -> int:
        ...

    def __bool__(self):  # -> bool:
        ...

    def up(self, count=...):  # -> RelativePath:
        ...

    def __radd__(self, path):
        ...
