"""
This type stub file was generated by pyright.
"""


from contextlib import contextmanager
from plumbum.path.base import Path

logger = ...
_EMPTY = ...


class LocalPath(Path):
    """The class implementing local-machine paths"""

    CASE_SENSITIVE = ...

    def __new__(cls, *parts):  # -> LocalPath | Self:
        ...

    @property

    def name(self):  # -> str:
        ...

    @property

    def dirname(self):  # -> LocalPath:
        ...

    @property

    def suffix(self):  # -> str:
        ...

    @property

    def suffixes(self):  # -> list[Any]:
        ...

    @property

    def uid(self):  # -> FSUser:
        ...

    @property

    def gid(self):  # -> FSUser:
        ...

    def join(self, *others):  # -> LocalPath:
        ...

    def list(self):  # -> list[Self]:
        ...

    def iterdir(self):  # -> Generator[Self, None, None]:
        ...

    def is_dir(self):  # -> bool:
        ...

    def is_file(self):  # -> bool:
        ...

    def is_symlink(self):  # -> bool:
        ...

    def exists(self):  # -> bool:
        ...

    def stat(self):  # -> stat_result:
        ...

    def with_name(self, name):  # -> Any:
        ...

    @property

    def stem(self):  # -> str:
        ...

    def with_suffix(self, suffix, depth=...):  # -> LocalPath:
        ...

    def glob(self, pattern):  # -> list[Any]:
        ...

    def delete(self):  # -> None:
        ...

    def move(self, dst):  # -> LocalPath:
        ...

    def copy(self, dst, override=...):  # -> LocalPath:
        ...

    def mkdir(self, mode=..., parents=..., exist_ok=...):  # -> None:
        ...

    def open(self, mode=..., encoding=...):  # -> IO[Any]:
        ...

    def read(self, encoding=..., mode=...):  # -> Any:
        ...

    def write(self, data, encoding=..., mode=...):  # -> None:
        ...

    def touch(self):  # -> None:
        ...

    def chown(self, owner=..., group=..., recursive=...):  # -> None:
        ...

    def chmod(self, mode):  # -> None:
        ...

    def access(self, mode=...):  # -> bool:
        ...

    def link(self, dst):  # -> None:
        ...

    def symlink(self, dst):  # -> None:
        ...

    def unlink(self):  # -> None:
        ...

    def as_uri(self, scheme=...):  # -> str:
        ...

    @property

    def drive(self):  # -> str:
        ...

    @property

    def root(self):  # -> str:
        ...


class LocalWorkdir(LocalPath):
    """Working directory manipulator"""

    def __hash__(self) -> int:
        ...

    def __new__(cls):  # -> LocalPath | Self:
        ...

    def chdir(self, newdir):  # -> Self:
        """Changes the current working directory to the given one

        :param newdir: The destination director (a string or a ``LocalPath``)
        """
        ...

    def getpath(self):  # -> LocalPath:
        """Returns the current working directory as a ``LocalPath`` object"""
        ...

    @contextmanager

    def __call__(self, newdir):  # -> Generator[Self, Any, None]:
        """A context manager used to ``chdir`` into a directory and then ``chdir`` back to
        the previous location; much like ``pushd``/``popd``.

        :param newdir: The destination directory (a string or a ``LocalPath``)
        """
        ...
