"""
This type stub file was generated by pyright.
"""


from contextlib import contextmanager
from plumbum.path.base import Path


class StatRes:
    """POSIX-like stat result"""

    def __init__(self, tup) -> None:
        ...

    def __getitem__(self, index):
        ...

    mode = ...
    ino = ...
    dev = ...
    nlink = ...
    uid = ...
    gid = ...
    size = ...
    atime = ...
    mtime = ...
    ctime = ...


class RemotePath(Path):
    """The class implementing remote-machine paths"""

    def __new__(cls, remote, *parts):  # -> Self:
        ...

    @property

    def name(self):  # -> str:
        ...

    @property

    def dirname(self):  # -> str | Self:
        ...

    @property

    def suffix(self):  # -> str:
        ...

    @property

    def suffixes(self):  # -> list[Any]:
        ...

    @property

    def uid(self):  # -> FSUser:
        ...

    @property

    def gid(self):  # -> FSUser:
        ...

    def join(self, *parts):  # -> RemotePath:
        ...

    def list(self):  # -> list[Any] | list[RemotePath]:
        ...

    def iterdir(self):  # -> tuple[()] | Generator[RemotePath, None, None]:
        ...

    def is_dir(self):  # -> Literal[False]:
        ...

    def is_file(self):  # -> bool:
        ...

    def is_symlink(self):  # -> Literal[False]:
        ...

    def exists(self):  # -> bool:
        ...

    def stat(self):
        ...

    def with_name(self, name):  # -> Any:
        ...

    def with_suffix(self, suffix, depth=...):  # -> Self:
        ...

    def glob(self, pattern):  # -> list[Any]:
        ...

    def delete(self):  # -> None:
        ...
    unlink = ...

    def move(self, dst):  # -> None:
        ...

    def copy(self, dst, override=...):  # -> None:
        ...

    def mkdir(self, mode=..., parents=..., exist_ok=...):  # -> None:
        ...

    def read(self, encoding=...):
        ...

    def write(self, data, encoding=...):  # -> None:
        ...

    def touch(self):  # -> None:
        ...

    def chown(self, owner=..., group=..., recursive=...):  # -> None:
        ...

    def chmod(self, mode):  # -> None:
        ...

    def access(self, mode=...):  # -> Literal[False]:
        ...

    def link(self, dst):  # -> None:
        ...

    def symlink(self, dst):  # -> None:
        ...

    def open(self, mode=..., bufsize=..., *, encoding=...):
        """
        Opens this path as a file.

        Only works for ParamikoMachine-associated paths for now.
        """
        ...

    def as_uri(self, scheme=...):  # -> str:
        ...

    @property

    def stem(self):  # -> str:
        ...

    @property

    def root(self):  # -> Literal['/']:
        ...

    @property

    def drive(self):  # -> Literal['']:
        ...


class RemoteWorkdir(RemotePath):
    """Remote working directory manipulator"""

    def __new__(cls, remote):  # -> Self:
        ...

    def __hash__(self) -> int:
        ...

    def chdir(self, newdir):  # -> Self:
        """Changes the current working directory to the given one"""
        ...

    def getpath(self):  # -> RemotePath:
        """Returns the current working directory as a
        `remote path <plumbum.path.remote.RemotePath>` object"""
        ...

    @contextmanager

    def __call__(self, newdir):  # -> Generator[Self, Any, None]:
        """A context manager used to ``chdir`` into a directory and then ``chdir`` back to
        the previous location; much like ``pushd``/``popd``.

        :param newdir: The destination director (a string or a
                       :class:`RemotePath <plumbum.path.remote.RemotePath>`)
        """
        ...
