"""
This type stub file was generated by pyright.
"""


"""
  Copyright 2011 Jeff Garzik

  AuthServiceProxy has the following improvements over python-jsonrpc's
  ServiceProxy class:

  - HTTP connections persist for the life of the AuthServiceProxy object
    (if server supports HTTP/1.1)
  - sends protocol 'version', per JSON-RPC 1.1
  - sends proper, incrementing 'id'
  - sends Basic HTTP authentication headers
  - parses all JSON numbers that look like floats as Decimal
  - uses standard Python json lib

  Previous copyright, from python-jsonrpc/jsonrpc/proxy.py:

  Copyright (c) 2007 Jan-Klaas Kollhof

  This file is part of jsonrpc.

  jsonrpc is free software; you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as published by
  the Free Software Foundation; either version 2.1 of the License, or
  (at your option) any later version.

  This software is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU Lesser General Public License for more details.

  You should have received a copy of the GNU Lesser General Public License
  along with this software; if not, write to the Free Software
  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
"""
USER_AGENT = ...
HTTP_TIMEOUT = ...
log = ...


class JSONRPCException(Exception):

    def __init__(self, rpc_error) -> None:
        ...

    def __str__(self) -> str:
        ...

    def __repr__(self):  # -> str:
        ...


def EncodeDecimal(o):  # -> float:
    ...


class AuthServiceProxy:
    __id_count = ...

    def __init__(self, service_url, service_name=..., timeout=..., connection=...) -> None:
        ...

    def __getattr__(self, name):  # -> AuthServiceProxy:
        ...

    def __call__(self, *args):  # -> Any:
        ...

    def batch_(self, rpc_calls):  # -> list[Any]:
        """Batch RPC call.
        Pass array of arrays: [ [ "method", params... ], ... ]
        Returns array of results.
        """
        ...
