"""
This type stub file was generated by pyright.
"""


from pathlib import Path
from typing import Any, Literal
from PIL import Image
from .._types import Writeable
from . import base


class PilImage(base.BaseImage):
    kind: Literal["PNG"]
    fill_color: str

    def new_image(self, *, back_color: str = ..., fill_color: str = ..., **kwargs: Any) -> Image.Image:
        ...

    def get_image(self, **kwargs: Any) -> Image.Image:
        ...

    def drawrect(self, row: int, col: int) -> None:
        ...

    def save(
        self,
        stream: str | bytes | Path | Writeable,
        format: str | None = ...,
        *,
        kind: str | None = ...,
        save_all: bool = ...,
        bitmap_format: Literal["bmp", "png"] = ...,
        optimize: bool = ...,
        **kwargs: Any,
    ) -> None: ...

    def __getattr__(self, name: str) -> Any:
        ...
