"""
This type stub file was generated by pyright.
"""


from . import utils
from .generate import compose_mail, send_mail, send_mail2
from .parse import PyzMessage, PzMessage, decode_text, email_address_re, message_from_binary_file, message_from_bytes, message_from_file, message_from_string
from .version import __version__

__all__ = [
    "compose_mail",
    "send_mail",
    "send_mail2",
    "email_address_re",
    "PyzMessage",
    "PzMessage",
    "decode_text",
    "__version__",
    "utils",
    "generate",
    "parse",
    "version",
    "message_from_string",
    "message_from_file",
    "message_from_binary_file",
    "message_from_bytes",
]
