"""
This type stub file was generated by pyright.
"""


from rpyc.core.stream import PipeStream, SocketStream, TunneledSocketStream
from rpyc.core.channel import Channel
from rpyc.core.protocol import Connection, DEFAULT_CONFIG
from rpyc.core.netref import BaseNetref
from rpyc.core.async_ import AsyncResult, AsyncResultTimeout
from rpyc.core.service import ClassicService, MasterService, Service, SlaveService, VoidService
from rpyc.core.vinegar import GenericException
