"""
This type stub file was generated by pyright.
"""


"""*Channel* is an abstraction layer over streams that works with *packets of data*,
rather than an endless stream of bytes, and adds support for compression.
"""
zlib = ...


class Channel:
    """Channel implementation.

    Note: In order to avoid problems with all sorts of line-buffered transports,
    we deliberately add ``\\n`` at the end of each frame.
    """

    COMPRESSION_THRESHOLD = ...
    COMPRESSION_LEVEL = ...
    FRAME_HEADER = ...
    FLUSHER = ...
    __slots__ = ...

    def __init__(self, stream, compress=...) -> None:
        ...

    def close(self):  # -> None:
        """closes the channel and underlying stream"""
        ...

    @property

    def closed(self):
        """indicates whether the underlying stream has been closed"""
        ...

    def fileno(self):
        """returns the file descriptor of the underlying stream"""
        ...

    def poll(self, timeout):
        """polls the underlying steam for data, waiting up to *timeout* seconds"""
        ...

    def recv(self):  # -> Any:
        """Receives the next packet (or *frame*) from the underlying stream.
        This method will block until the packet has been read completely

        :returns: string of data
        """
        ...

    def send(self, data):  # -> None:
        """Sends the given string of data as a packet over the underlying
        stream. Blocks until the packet has been sent.

        :param data: the byte string to send as a packet
        """
        ...
