"""
This type stub file was generated by pyright.
"""


"""*NetRef*: a transparent *network reference*. This module contains quite a lot
of *magic*, so beware.
"""
builtin_id_pack_cache = ...
builtin_classes_cache = ...
DELETED_ATTRS = ...
LOCAL_ATTRS = ...
_builtin_types = ...
_normalized_builtin_types = ...


def syncreq(proxy, handler, *args):  # -> Any:
    """Performs a synchronous request on the given proxy object.
    Not intended to be invoked directly.

    :param proxy: the proxy on which to issue the request
    :param handler: the request handler (one of the ``HANDLE_XXX`` members of
                    ``rpyc.protocol.consts``)
    :param args: arguments to the handler

    :raises: any exception raised by the operation will be raised
    :returns: the result of the operation
    """
    ...


def asyncreq(proxy, handler, *args):  # -> Any:
    """Performs an asynchronous request on the given proxy object.
    Not intended to be invoked directly.

    :param proxy: the proxy on which to issue the request
    :param handler: the request handler (one of the ``HANDLE_XXX`` members of
                    ``rpyc.protocol.consts``)
    :param args: arguments to the handler

    :returns: an :class:`~rpyc.core.async_.AsyncResult` representing
              the operation
    """
    ...


class NetrefMetaclass(type):
    """A *metaclass* used to customize the ``__repr__`` of ``netref`` classes.
    It is quite useless, but it makes debugging and interactive programming
    easier"""

    __slots__ = ...

    def __repr__(self):  # -> str:
        ...


class BaseNetref(metaclass=NetrefMetaclass):
    """The base netref class, from which all netref classes derive. Some netref
    classes are "pre-generated" and cached upon importing this module (those
    defined in the :data:`_builtin_types`), and they are shared between all
    connections.

    The rest of the netref classes are created by :meth:`rpyc.core.protocol.Connection._unbox`,
    and are private to the connection.

    Do not use this class directly; use :func:`class_factory` instead.

    :param conn: the :class:`rpyc.core.protocol.Connection` instance
    :param id_pack: id tuple for an object ~ (name_pack, remote-class-id, remote-instance-id)
        (cont.) name_pack := __module__.__name__ (hits or misses on builtin cache and sys.module)
                remote-class-id := id of object class (hits or misses on netref classes cache and instance checks)
                remote-instance-id := id object instance (hits or misses on proxy cache)
        id_pack is usually created by rpyc.lib.get_id_pack
    """

    __slots__ = ...

    def __init__(self, conn, id_pack) -> None:
        ...

    def __del__(self):  # -> None:
        ...

    def __getattribute__(self, name):  # -> Any:
        ...

    def __getattr__(self, name):  # -> Any:
        ...

    def __delattr__(self, name):  # -> None:
        ...

    def __setattr__(self, name, value):  # -> None:
        ...

    def __dir__(self):  # -> list[Any]:
        ...

    def __hash__(self) -> int:
        ...

    def __cmp__(self, other):  # -> Any:
        ...

    def __eq__(self, other) -> bool:
        ...

    def __ne__(self, other) -> bool:
        ...

    def __lt__(self, other) -> bool:
        ...

    def __gt__(self, other) -> bool:
        ...

    def __le__(self, other) -> bool:
        ...

    def __ge__(self, other) -> bool:
        ...

    def __repr__(self):  # -> Any:
        ...

    def __str__(self) -> str:
        ...

    def __exit__(self, exc, typ, tb):  # -> Any:
        ...

    def __reduce_ex__(self, proto):  # -> tuple[Any, tuple[Any]]:
        ...

    def __instancecheck__(self, other):  # -> Any | bool | None:
        ...


class NetrefClass:
    """a descriptor of the class being proxied

    Future considerations:
     + there may be a cleaner alternative but lib.compat.with_metaclass prevented using __new__
     + consider using __slot__ for this class
     + revisit the design choice to use properties here
    """

    def __init__(self, class_obj) -> None:
        ...
    @property

    def instance(self):  # -> Any:
        """accessor to class object for the instance being proxied"""
        ...

    @property

    def owner(self):
        """accessor to the class object for the instance owner being proxied"""
        ...

    def __get__(self, netref_instance, netref_owner):  # -> Any:
        """the value returned when accessing the netref class is dictated by whether or not an instance is proxied"""
        ...


def class_factory(id_pack, methods):  # -> Any:
    """Creates a netref class proxying the given class

    :param id_pack: the id pack used for proxy communication
    :param methods: a list of ``(method name, docstring)`` tuples, of the methods that the class defines

    :returns: a netref class
    """
    ...
