"""
This type stub file was generated by pyright.
"""


"""The RPyC protocol
"""


class PingError(Exception):
    """The exception raised should :func:`Connection.ping` fail"""

    ...

UNBOUND_THREAD_ID = ...
DEFAULT_CONFIG = ...
_connection_id_generator = ...


class Connection:
    """The RPyC *connection* (AKA *protocol*).

    Objects referenced over the connection are either local or remote. This class retains a strong reference to
    local objects that is deleted when the reference count is zero. Remote/proxied objects have a life-cycle
    controlled by a different address space. Since garbage collection is handled on the remote end, a weak reference
    is used for netrefs.

    :param root: the :class:`~rpyc.core.service.Service` object to expose
    :param channel: the :class:`~rpyc.core.channel.Channel` over which messages are passed
    :param config: the connection's configuration dict (overriding parameters
                   from the :data:`default configuration <DEFAULT_CONFIG>`)
    """

    def __init__(self, root, channel, config=...) -> None:
        ...

    def __del__(self):  # -> None:
        ...

    def __enter__(self):  # -> Self:
        ...

    def __exit__(self, t, v, tb):  # -> None:
        ...

    def __repr__(self):  # -> str:
        ...

    def close(self):  # -> None:
        """closes the connection, releasing all held resources"""
        ...

    @property

    def closed(self):  # -> bool:
        """Indicates whether the connection has been closed or not"""
        ...

    def fileno(self):
        """Returns the connectin's underlying file descriptor"""
        ...

    def ping(self, data=..., timeout=...):  # -> None:
        """Asserts that the other party is functioning properly, by making sure
        the *data* is echoed back before the *timeout* expires

        :param data: the data to send (leave ``None`` for the default buffer)
        :param timeout: the maximal time to wait for echo

        :raises: :class:`PingError` if the echoed data does not match
        :raises: :class:`EOFError` if the remote host closes the connection
        """
        ...

    def serve(self, timeout=..., wait_for_lock=..., waiting=...):  # -> bool:
        """Serves a single request or reply that arrives within the given
        time frame (default is 1 sec). Note that the dispatching of a request
        might trigger multiple (nested) requests, thus this function may be
        reentrant.

        :returns: ``True`` if a request or reply were received, ``False`` otherwise.
        """
        ...

    def poll(self, timeout=...):  # -> bool:
        """Serves a single transaction, should one arrives in the given
        interval. Note that handling a request/reply may trigger nested
        requests, which are all part of a single transaction.

        :returns: ``True`` if a transaction was served, ``False`` otherwise"""
        ...

    def serve_all(self):  # -> None:
        """Serves all requests and replies for as long as the connection is
        alive."""
        ...

    def serve_threaded(self, thread_count=...):  # -> None:
        """Serves all requests and replies for as long as the connection is alive.

        CAVEAT: using non-immutable types that require a netref to be constructed to serve a request,
        or invoking anything else that performs a sync_request, may timeout due to the sync_request reply being
        received by another thread serving the connection. A more conventional approach where each client thread
        opens a new connection would allow `ThreadedServer` to naturally avoid such multiplexing issues and
        is the preferred approach for threading procedures that invoke sync_request. See issue #345
        """
        ...

    def poll_all(self, timeout=...):  # -> bool:
        """Serves all requests and replies that arrive within the given interval.

        :returns: ``True`` if at least a single transaction was served, ``False`` otherwise
        """
        ...

    def sync_request(self, handler, *args):  # -> None:
        """requests, sends a synchronous request (waits for the reply to arrive)

        :raises: any exception that the requests may be generated
        :returns: the result of the request
        """
        ...

    def async_request(self, handler, *args, **kwargs):  # -> AsyncResult:
        """Send an asynchronous request (does not wait for it to finish)

        :returns: an :class:`rpyc.core.async_.AsyncResult` object, which will
                  eventually hold the result (or exception)
        """
        ...

    @property

    def root(self):  # -> None:
        """Fetches the root object (service) of the other party"""
        ...


class _Thread:
    """Internal thread information for the RPYC protocol used for thread binding."""

    def __init__(self, id) -> None:
        ...
