"""
This type stub file was generated by pyright.
"""


import sys

"""
An abstraction layer over OS-dependent file-like objects, that provides a
consistent view of a *duplex byte stream*.
"""
win32file = ...
win32pipe = ...
win32event = ...
ssl = ...
retry_errnos = ...


class Stream:
    """Base Stream"""

    __slots__ = ...

    def close(self):
        """closes the stream, releasing any system resources associated with it"""
        ...

    @property

    def closed(self):
        """tests whether the stream is closed or not"""
        ...

    def fileno(self):
        """returns the stream's file descriptor"""
        ...

    def poll(self, timeout):  # -> bool:
        """indicates whether the stream has data to read (within *timeout*
        seconds)"""
        ...

    def read(self, count):
        """reads **exactly** *count* bytes, or raise EOFError

        :param count: the number of bytes to read

        :returns: read data
        """
        ...

    def write(self, data):
        """writes the entire *data*, or raise EOFError

        :param data: a string of binary data
        """
        ...

    def __enter__(self):  # -> Self:
        ...

    def __exit__(self, *exc_info):  # -> None:
        ...


class ClosedFile:
    """Represents a closed file object (singleton)"""

    __slots__ = ...

    def __getattr__(self, name):
        ...

    def close(self):  # -> None:
        ...

    @property

    def closed(self):  # -> Literal[True]:
        ...

    def fileno(self):
        ...

ClosedFile = ...


class SocketStream(Stream):
    """A stream over a socket"""

    __slots__ = ...
    MAX_IO_CHUNK = ...

    def __init__(self, sock) -> None:
        ...
    @classmethod

    def connect(cls, host, port, **kwargs):  # -> Self:
        """factory method that creates a ``SocketStream`` over a socket connected
        to *host* and *port*

        :param host: the host name
        :param port: the TCP port
        :param family: specify a custom socket family
        :param socktype: specify a custom socket type
        :param proto: specify a custom socket protocol
        :param timeout: connection timeout (default is 3 seconds)
        :param nodelay: set the TCP_NODELAY socket option
        :param keepalive: enable TCP keepalives. The value should be a boolean,
                          but on Linux, it can also be an integer specifying the
                          keepalive interval (in seconds)
        :param ipv6: if True, creates an IPv6 socket (``AF_INET6``); otherwise
                     an IPv4 (``AF_INET``) socket is created

        :returns: a :class:`SocketStream`
        """
        ...

    @classmethod

    def unix_connect(cls, path, timeout=...):  # -> Self:
        """factory method that creates a ``SocketStream`` over a unix domain socket
        located in *path*

        :param path: the path to the unix domain socket
        :param timeout: socket timeout
        """
        ...

    @classmethod

    def ssl_connect(cls, host, port, ssl_kwargs, **kwargs):
        """factory method that creates a ``SocketStream`` over an SSL-wrapped
        socket, connected to *host* and *port* with the given credentials.

        :param host: the host name
        :param port: the TCP port
        :param ssl_kwargs: a dictionary of keyword arguments for
                           ``ssl.SSLContext`` and ``ssl.SSLContext.wrap_socket``
        :param kwargs: additional keyword arguments: ``family``, ``socktype``,
                       ``proto``, ``timeout``, ``nodelay``, passed directly to
                       the ``socket`` constructor, or ``ipv6``.
        :param ipv6: if True, creates an IPv6 socket (``AF_INET6``); otherwise
                     an IPv4 (``AF_INET``) socket is created

        :returns: a :class:`SocketStream`
        """
        ...

    @property

    def closed(self):  # -> bool:
        ...

    def close(self):  # -> None:
        ...

    def fileno(self):
        ...

    def read(self, count):  # -> LiteralString:
        ...

    def write(self, data):  # -> None:
        ...


class TunneledSocketStream(SocketStream):
    """A socket stream over an SSH tunnel (terminates the tunnel when the connection closes)"""

    __slots__ = ...

    def __init__(self, sock) -> None:
        ...

    def close(self):  # -> None:
        ...


class PipeStream(Stream):
    """A stream over two simplex pipes (one used to input, another for output)"""

    __slots__ = ...
    MAX_IO_CHUNK = ...

    def __init__(self, incoming, outgoing) -> None:
        ...
    @classmethod

    def from_std(cls):  # -> Self:
        """factory method that creates a PipeStream over the standard pipes
        (``stdin`` and ``stdout``)

        :returns: a :class:`PipeStream` instance
        """
        ...

    @classmethod

    def create_pair(cls):  # -> tuple[Self, Self]:
        """factory method that creates two pairs of anonymous pipes, and
        creates two PipeStreams over them. Useful for ``fork()``.

        :returns: a tuple of two :class:`PipeStream` instances
        """
        ...

    @property

    def closed(self):  # -> bool:
        ...

    def close(self):  # -> None:
        ...

    def fileno(self):
        ...

    def read(self, count):  # -> LiteralString:
        ...

    def write(self, data):  # -> None:
        ...


class Win32PipeStream(Stream):
    """A stream over two simplex pipes (one used to input, another for output).
    This is an implementation for Windows pipes (which suck)"""

    __slots__ = ...
    PIPE_BUFFER_SIZE = ...
    MAX_IO_CHUNK = ...

    def __init__(self, incoming, outgoing) -> None:
        ...
    @classmethod

    def from_std(cls):  # -> Self:
        ...

    @classmethod

    def create_pair(cls):  # -> tuple[Self, Self]:
        ...

    def fileno(self):
        ...
    @property

    def closed(self):  # -> bool:
        ...

    def close(self):  # -> None:
        ...

    def read(self, count):  # -> LiteralString:
        ...

    def write(self, data):  # -> None:
        ...

    def poll(self, timeout, interval=...):  # -> bool:
        """a Windows version of select()"""
        ...


class NamedPipeStream(Win32PipeStream):
    """A stream over two named pipes (one used to input, another for output).
    Windows implementation."""

    NAMED_PIPE_PREFIX = ...
    PIPE_IO_TIMEOUT = ...
    CONNECT_TIMEOUT = ...

    def __init__(self, handle, is_server_side) -> None:
        ...
    @classmethod

    def from_std(cls):
        ...
    @classmethod

    def create_pair(cls):
        ...
    @classmethod

    def create_server(cls, pipename, connect=...):  # -> Self:
        """factory method that creates a server-side ``NamedPipeStream``, over
        a newly-created *named pipe* of the given name.

        :param pipename: the name of the pipe. It will be considered absolute if
                         it starts with ``\\\\.``; otherwise ``\\\\.\\pipe\\rpyc``
                         will be prepended.
        :param connect: whether to connect on creation or not

        :returns: a :class:`NamedPipeStream` instance
        """
        ...

    def connect_server(self):  # -> None:
        """connects the server side of an unconnected named pipe (blocks
        until a connection arrives)"""
        ...

    @classmethod

    def create_client(cls, pipename):  # -> Self:
        """factory method that creates a client-side ``NamedPipeStream``, over
        a newly-created *named pipe* of the given name.

        :param pipename: the name of the pipe. It will be considered absolute if
                         it starts with ``\\\\.``; otherwise ``\\\\.\\pipe\\rpyc``
                         will be prepended.

        :returns: a :class:`NamedPipeStream` instance
        """
        ...

    def close(self):  # -> None:
        ...

    def read(self, count):  # -> LiteralString:
        ...

    def write(self, data):  # -> None:
        ...

    def poll(self, timeout, interval=...):  # -> Any | Literal[True]:
        """Windows version of select()"""
        ...


if sys.platform == "win32":
    ...
